---
sidebar: sidebar 
permalink: change-tiering-policy.html 
keywords: tiering policy, change tier, change tiers, tier policy update 
summary: 變更 BlueXP  工作負載工廠的分層原則，將資料從高效能主儲存層重新分配至次容量集區儲存層。 
---
= 變更 BlueXP  工作負載工廠中磁碟區的分層原則
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
在 BlueXP  工作負載工廠中，您可以變更分層原則，以自動將資料從高效能主要儲存層重新分配至次要容量集區儲存層。

.關於這項工作
您可以隨時變更磁碟區的分層原則。分層原則是根據每個磁碟區來定義。

決定資料的儲存位置會影響您的成本節約效益。

適用於 ONTAP 的 FSX 有兩層可儲存 Volume 資料：

* * SSD 儲存層 * ：此主要儲存層適用於您最常存取的資料、也稱為 _hot_ 資料。在主要儲存層儲存資料的成本比在次要儲存層中要高。
* * 容量集區儲存層 * ：此次儲存層用於歸檔資料或不常存取的資料、也稱為 _cold 資料。


如需儲存層的詳細資訊、請參閱 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-storage-capacity.html#storage-tiers["管理儲存容量"^] AWS for FSX for NetApp ONTAP 文件中的。

.開始之前
變更分層原則之前，請先檢閱可用的分層原則。

* * 平衡（自動） * ：使用使用使用者介面建立磁碟區時，預設分層原則。在冷卻期間結束後，將經常存取的資料保留在 SSD 儲存層和不常存取的階層中，並將資料和快照保留到容量池儲存層。建議用於一般主要工作負載。
* * 成本最佳化（全部） * ：將所有快照和資料分層至容量集區儲存層。建議用於次要目標。
* * 效能最佳化（僅限快照） * ：將僅限階層的快照資料傳送至容量集區儲存層。建議用於低延遲工作負載，例如關鍵任務資料庫。
* * 無 * ：將磁碟區資料保留在 SSD 儲存層中，避免移至容量集區儲存層。


請注意、某些分層原則具有相關的最低冷卻週期、可設定磁碟區中的使用者資料必須保持非作用中狀態、才能將資料視為「冷」、並移至容量集區儲存層。當資料寫入磁碟時、冷卻週期即開始。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在儲存設備中、選取 * 移至儲存設備詳細目錄 * 。
. 在 *FSX for ONTAP * 標籤中，選取要更新磁碟區之檔案系統的三點功能表，然後選取 * 管理 * 。
. 從檔案系統總覽中、選取 * Volumes （磁碟區） * 標籤。
. 從 Volumes （磁碟區）索引標籤中，選取要變更分層原則的磁碟區三點功能表。
. 選擇 * 進階動作 * 、然後 * 變更分層原則 * 。
. 在「變更分層原則」頁面上，選取以複製來源磁碟區的分層原則，或選取下列其中一個分層原則：
+
** * 平衡（自動） * ：輸入冷卻天數。
** * 成本最佳化（全部） *
** * 效能最佳化（僅限快照） * ：輸入冷卻天數。
** *無*


. 選擇*應用*。

