---
sidebar: sidebar 
permalink: configuration-analysis.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations 
summary: NetApp Workload Factory 定期分析Amazon FSx for NetApp ONTAP檔案系統配置，以確定是否有任何問題。 
---
= 適用於 ONTAP 檔案系統的 FSX 組態分析
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory 定期分析Amazon FSx for NetApp ONTAP檔案系統配置，以確定是否有任何問題。當發現問題時，Workload Factory 會向您展示問題所在，並解釋需要進行哪些更改以確保您的檔案系統儲存達到最佳效能、成本效益並符合最佳實踐。

主要功能包括：

* 每日組態分析
* 自動最佳實務驗證
* 主動觀察
* 行動洞見
* AWS 架構良好的架構顧問




== 架構良好的狀態

在檔案系統層級的 Workload Factory 控制台中，列出了所有 FSx for ONTAP檔案系統的良好架構狀態。架構良好的狀態分為「問題」、「未分析」或「架構良好」。選擇良好架構狀態會將您重新導向至檔案系統內的良好架構狀態標籤，您可以在其中找到良好架構分數、設定類別以及檔案系統的所有設定。

架構良好的分數:: 分數包括所有目前分析的組態，並以百分比顯示。25% 的分數表示 25% 的檔案系統組態架構良好。
組態類別:: 檔案系統組態分為幾類，符合 AWS 架構良好的架構架構的下列五大支柱。
+
--
* _ 可靠性 _ ：確保工作負載能正確且一致地執行其預期功能，即使發生中斷也沒問題。ONTAP 備份的範例組態為 FSX 。
* _ 安全 _ ：強調透過風險評估和緩解策略來保護資料，系統和資產。
* 營運卓越 _ ：專注於提供最理想的架構和商業價值。
* 成本最佳化 _ ：旨在提供商業價值，同時將成本降至最低。
* _ 效能效率 _ ：專注於有效運用資源來滿足系統需求，並在需求改變時維持最佳效能。


--




== 分析需求

要進行完整的檔案系統分析，必須執行以下操作：

* 關聯連結。連結連接使 Workload Factory 能夠分析所有檔案系統配置，例如資料保護和效能。
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何關聯現有連結或建立並關聯新連結"]。

* 在您的 AWS 帳戶中授予_檢視、規劃和分析_權限。
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["瞭解如何授予 AWS 帳戶權限"^]



.下一步
link:improve-configurations.html["實作架構良好的檔案系統組態"]
