---
sidebar: sidebar 
permalink: configure-active-directory.html 
keywords: configure AD, configure active directory, update ad, edit active directory 
summary: 在NetApp Workload Factory 中為 FSx for ONTAP檔案系統中的儲存虛擬機器設定和更新 Active Directory。 
---
= 設定及更新儲存 VM 的 Active Directory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
在NetApp Workload Factory 中為 FSx for ONTAP檔案系統中的儲存虛擬機器設定和更新 Active Directory。

.關於這項工作
同樣的步驟也適用於設定及更新儲存 VM 的 Active Directory 。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在儲存圖塊中，選擇*轉到儲存*。
. 從儲存選單中，選擇 *FSx for ONTAP*。
. 從 *FSx for ONTAP* 中，選擇要更新的儲存虛擬機器的檔案系統的操作選單，然後選擇 *管理*。
. 從檔案系統總覽中、選取 * 儲存 VMS* 標籤。
. 從「儲存虛擬機器」標籤中，選擇要為其設定 Active Directory 的儲存虛擬機器的操作選單。
. 選取 * 管理 AD 組態 * 。
. 在「管理 AD 組態」頁面上、提供下列項目：
+
.. * 要加入的 Active Directory 網域 * ：輸入 Active Directory 的完整網域名稱（ FQDN ）。
.. * DNS IP 位址 * ：輸入最多三個 IP 位址、並以逗號分隔。
.. *SMB 伺服器 NetBIOS 名稱 * ：輸入 Active Directory 電腦物件的 SMB 伺服器 NetBIOS 名稱、以建立儲存 VM 。這是 Active Directory 中此 SVM 的名稱。
.. * 使用者名稱 * ：在現有的 Active Directory 中輸入服務帳戶的使用者名稱。
+
請勿包含網域首碼或尾碼。對於 `EXAMPLE\ADMIN`，請使用 `ADMIN`。

.. * 密碼 * ：輸入服務帳戶的密碼。
.. * 組織單位（ OU ） * ：輸入組織單位。
+
OU 是您要加入檔案系統之組織單位的辨別路徑名稱。

.. * 委派系統管理員群組 * ：選擇性地輸入委派的檔案系統管理員群組。
+
委派的系統管理員群組是 Active Directory 中可管理檔案系統的群組名稱。

+
如果您使用的是 AWS 託管的 Microsoft AD 、則必須指定群組、例如 AWS 委派的 FSX 管理員、 AWS 委派管理員、或是具有 OU 委派權限的自訂群組。

+
如果您要連線至自我管理的 AD 、請使用 AD 中的群組名稱。預設群組為 `Domain Admins`。



. 選擇*應用*。

