---
sidebar: sidebar 
permalink: configuration-analysis.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations 
summary: NetApp Workload Factory 會定期分析 Amazon FSx for NetApp ONTAP 檔案系統組態，以判斷是否有任何組態問題。 
---
= 適用於 ONTAP 檔案系統的 FSX 組態分析
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory 會定期分析 Amazon FSx for NetApp ONTAP 檔案系統設定，以判斷是否存在任何設定問題。當發現問題時，Workload Factory 會顯示這些問題並說明需要做出哪些更改，以確保您的檔案系統儲存能達到最佳效能、成本效益及符合最佳實務。

主要功能包括：

* 每日組態分析
* 自動最佳實務驗證
* 主動觀察
* 行動洞見
* AWS 架構良好的架構顧問




[[how-it-works]]
== 運作方式

Workload Factory 每日分析您在支援的雲端儲存系統部署上執行的工作負載。此分析提供架構完善的狀態資訊、洞察分析和建議。

每日分析完成後，組態在部署的架構完善儀表板中會顯示為「最佳化的」或「未最佳化的」。您可以按類別查看組態問題，以及組態問題清單和建議。您可以審查針對組態問題的建議。Workload Factory 可以自動修復某些問題；其他問題則需要手冊干預。在這種情況下，Workload Factory 會提供詳細說明，幫助您實作建議的變更。

您可以忽略不適用於您環境的組態分析。這樣可以避免不必要的警示和不準確的最佳化結果。

您也可以使用純文字語言建立自訂規則，以根據組織的標準和 NetApp 最佳實務來驗證您的環境。先進行模擬執行測試規則，然後排程在您的環境中執行。link:https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["深入瞭解自訂規則"^]。



[[why-it-matters]]
== 為什麼這很重要

Workload Factory 藉由結合後續評估與建議洞察和修復，將最佳實務做法應用於大型儲存設備、資料庫和 VMware 環境。自動化修復可減少人為錯誤，確保統一管理，並維護工作負載基礎架構的效能和可靠性。



[[analysis-requirements]]
== 分析需求

要進行完整的檔案系統分析，必須執行以下操作：

* 關聯連結。連結連接使 Workload Factory 能夠分析所有檔案系統配置，例如資料保護和效能。
+
link:https://docs.netapp.com/us-en/workload-setup-admin/create-link.html["了解如何關聯現有連結或建立並關聯新連結"^]。

* 在您的 AWS 帳戶中授予_檢視、規劃和分析_權限。
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["瞭解如何授予 AWS 帳戶權限"^]。





[[best-practices-and-recommendations-for-storage-workloads]]
== 儲存工作負載的最佳實務做法和建議

架構完善的儀表板會根據 ONTAP 最佳實務和 AWS Well-Architected Framework 評估儲存組態。此評估也會建議改進措施和修正方法。

精心設計的分析將組態分類為架構的下列要素：_可靠性_、_安全性_、_卓越營運_、_成本最佳化_和_效能效率_。



[[reliability]]
=== 可靠性

可靠性確保工作負載即使在出現中斷的情況下也能正確、持續地執行其預期功能。

* *Volume 備份*
+
備份磁碟區有助於滿足資料保留和合規性需求。使用磁碟區備份來設定資料的自動備份和保留。

* *Snapshot 原則*
+
排程本機 Snapshot 快照技術，以實現高效備份和快速還原。Snapshot 快照技術是 Volume 的即時時間點映像。此建議不適用於資料庫環境。

* *應用程式一致性快照*
+
對於資料庫環境，請搭配 NetApp SnapCenter 使用應用程式一致性快照，以便在特定時間點對 Volume 資料進行準確可靠的快照。這可確保應用程式流暢運作並保障資料安全。SnapCenter 能簡化備份流程，幫助您快速且準確地還原資料，從而減少停機並保護最重要的工作負載。

* * 跨區域複寫 *
+
跨區域複寫可確保您的資料複寫到另一個 AWS 區域，從而增強資料持久性和可用度。設定跨區域複寫以支援災難恢復和法規遵循。

* *SSD 容量餘裕*
+
SSD 儲存層的容量使用率不得超過 80%。否則可能會影響容量資源池儲存層的資料讀寫，進而影響檔案系統的處理量。當容量耗盡時，資料 Volume 將變為唯讀狀態。嘗試寫入新資料的服務也會失敗。

* *複製原則標籤*
+
來源磁碟區的快照原則標籤和複寫原則標籤必須相符，以確保資料可靠性。

* *檔案物件容量*
+
應提高檔案容量臨界值，以避免達到 Volume 容量限制。檔案容量（inodes）過低會阻止向 Volume 寫入更多資料。Workload Factory 建議將檔案容量使用率保持在 80% 以下，以允許建立新檔案。





[[security]]
=== 安全性

安全重點在於透過風險評估和緩解策略來保護資料、系統和資產。

* *勒索軟體保護（ARP/AI）*
+
NetApp 具備人工智慧的自主勒索軟體防護（ARP/AI）可協助您保護磁碟區免受勒索軟體威脅。Workload Factory 建議為所有磁碟區啟用 ARP/AI。

* *未經授權的 iSCSI Volume 存取*
+
使用 iSCSI 儲存應用程式資料的 Volume 不應同時允許 NAS 存取。Workload Factory 建議限制 iSCSI Volume 使用任何其他通訊協定。





[[operational-excellence]]
=== 卓越營運

卓越營運的重點在於提供最佳架構和業務價值。

* *自動容量管理*
+
應啟用自動容量管理，以定期確保 SSD 層不超過閾值。

* *Volume 容量餘裕*
+
為避免對應用程式讀寫造成潛力影響，請將 Volume 使用率保持在 80% 以下。您可以手動增加容量，或使用 Volume 自動擴充。

* *FlexCache 寫入模式*
+
為了獲得最佳效能，請根據您的工作負載設定快取關係寫入模式。對於讀取密集型、處理小檔案的工作負載，環繞寫入模式可提供更好的效能；而對於寫入密集型、處理大檔案的工作負載，回寫模式可提供更好的效能。

* *FlexCache® 複本大小*
+
啟用快取 Volume 自動調整規模和清理功能，以保持最佳大小並將快取集中用於熱資料，從而達到尖峰效率。

* *主機可見容量報告*
+
啟用主機可見的容量報告，以提供對 Volume 層級儲存設備使用情況的更佳可見度。

* *作業系統 （OS） 類型*
+
確認 ONTAP LUN 作業系統（OS）類型值與作業系統分割區方案相符，以達成 I/O 對齊。不正確的組態可能會降低效能。

* *區塊設備空間管理*
+
設定資料庫主機執行個體使用的 LUN 的區塊裝置空間設定，以防止寫入失敗並提高 FSx for ONTAP 的空間效率。此組態適用於資源隨需配置 Volume 的建議設定組合：保留空間、空間分配和部分保留。

* *資源隨需配置*
+
為託管資料庫執行個體的 FSx for ONTAP Volume 設定資源隨需配置。此方法允許儲存比實體可用空間更多的邏輯資料。





[[cost-optimization]]
=== 成本最佳化

成本優化可協助您在保持低成本的同時，為企業創造最大價值。

* *冷資料分層*
+
啟用冷資料分層以降低 SSD 儲存層的使用率。將分層原則套用至每個著重於一般資料儲存設備的 Volume。對於資料庫 Volume，請在適當情況下啟用冷資料分層。FSx for ONTAP 會持續掃描資料以尋找冷資料，並將其移至容量資源池層，而不會造成中斷。

* *儲存效率*
+
啟用儲存設備效率提升（資料精簡、壓縮和重複資料刪除），以最佳化儲存使用率並降低 SSD 分層成本。

* *備份到期*
+
刪除已刪除 Volume 的所有手動建立的備份，以及超過兩週的任何備份。這些備份不會自動過期，如果您不再需要將其用於 SLA 或恢復，則可能會增加成本並增加複雜性。

* *Snapshot 快照技術到期*
+
刪除不再需要的舊快照或手動建立的快照。刪除它們可以降低成本並減少系統混亂，尤其是在它們並非滿足您的服務等級協定（SLA）或恢復需求的情況下。

* *非作用中區塊裝置*
+
在區塊裝置七天未使用後，請歸檔區塊裝置資料或刪除未使用的區塊裝置，以降低成本。

* *超額配置的固態硬碟容量*
+
過多的 SSD 容量會增加不必要的成本。減少 SSD 分層，同時維持 20% 的可用空間緩衝區。此操作可能需要數小時到數天，在此期間不支援其他檔案系統操作。

* *非使用中的 NAS Volume*
+
組態分析會識別出未經常使用的 NAS Volume，並建議刪除或歸檔這些 Volume 以降低成本。





[[performance-efficiency]]
=== 效能效率

效能效率有助於確保有效利用儲存資源，並使工作負載以最佳狀態運作。

* *FlexGroup Volume 重新平衡*
+
重新平衡您的 FlexGroup Volume 以提高效率。擴充後，容量和工作負載活動可能會在整個 Volume 上變得不平衡。

* *FlexVol® Volume 重新平衡*
+
重新平衡您的 FlexVol Volume 以提高效率。擴充後，容量和工作負載活動可能會在整個 Volume 上變得不平衡。



.下一步
link:improve-configurations.html["實作架構良好的檔案系統組態"]
