---
sidebar: sidebar 
permalink: create-volume.html 
keywords: create volume, FSx for ONTAP volume 
summary: 設定 FSx for ONTAP 檔案系統後，在工作負載工廠中建立 FSx for ONTAP 磁碟區。 
---
= 在工作負載工廠中建立 FSx for ONTAP 卷
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
設定 FSx for ONTAP 檔案系統後，在工作負載工廠中建立 FSx for ONTAP 磁碟區作為用於對資料進行分組的虛擬資源。

.關於這項工作
FSx for ONTAP 磁碟區以虛擬方式將資料分組，決定資料的儲存方式，並決定資料的存取類型。Volume 不會消耗檔案系統儲存容量。儲存在磁碟區中的資料主要會消耗 SSD 儲存設備。視磁碟區的分層原則而定、資料可能也會佔用容量集區儲存空間。您可以在建立磁碟區時設定磁碟區的大小、稍後也可以變更其大小。

您的磁碟區可能會使用下列通訊協定：

* SMB/CIFS：Windows作業系統的檔案儲存協議
* NFS ：適用於 Unix 作業系統的檔案儲存傳輸協定
* iSCSI ：區塊儲存傳輸協定


.開始之前
建立 Volume 之前、請先檢閱下列先決條件：

* 您必須在工作負載工廠控制台中擁有 FSx for ONTAP 檔案系統。
* 您必須擁有儲存 VM 。
* 若要存取傳輸協定、請完成下列步驟：
+
** 要配置對卷的訪問，您必須關聯一個連結。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何關聯現有連結或建立並關聯新連結"]。連結建立關聯後，請返回此作業。
** 您必須為所選協定（SMB/CIFS、NFS 或 iSCSI）配置存取權限。






== 建立Volume

您可以使用 Codebox 中提供的下列工具來建立 Volume ： REST API ， CloudForformation 和 Terraform 。link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["瞭解如何使用 Codebox 進行自動化"^]。


NOTE: 從 Codebox 使用 Terraform 時、您複製或下載的程式碼會隱藏 `fsxadmin` 和 `vsadmin` 密碼。執行程式碼時、您需要重新輸入密碼。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在儲存設備中、選取 * 移至儲存設備詳細目錄 * 。
. 在 *FSX for ONTAP * 標籤中，選取您要在其中建立 Volume 的檔案系統三點功能表，然後選取 * 建立 Volume * 。
. 在「一般詳細資料」下的「建立 Volume 」頁面上、提供下列詳細資料：
+
.. * Volume 名稱 * ：輸入磁碟區的名稱。
.. * 儲存 VM 名稱 * ：選擇性地輸入儲存 VM 名稱。
.. * Volume 樣式 * ：選擇 * FlexVol * 或 * FlexGroup * Volume 。
+
FlexVol Volume 樣式預設為選取。

+
FlexGroup 磁碟區大小取決於組成部分的數量，每個組成部分需要 100 GiB。

.. * Volume Size* ：輸入 Volume 大小和單位。
+
也可以啟用 Volume 自動擴充。當您選擇 * 檔案存取 * 作為磁碟區存取類型時、即可使用此選項。

.. 磁碟區自動成長：選配啟用磁碟區自動成長功能，自動擴充磁碟區容量，直到達到最大容量。此功能可適應不斷增長的數據使用量，確保運作不會中斷。
+
指定卷的最大增長大小和單位。不能將最大成長大小設定為小於目前磁碟區大小

.. * 標記 * ：您可以選擇性地新增最多 50 個標記。


. 在 Access （僅適用於具有相關連結的檔案系統）下、提供下列詳細資料：
+
.. * 存取類型 * ：選取 * 檔案存取 * 或 * 封鎖存取 * 。設定磁碟區存取的其他欄位會因您的選擇而異。
+
*** * 檔案存取 * ：允許多個授權使用者和裝置使用 SMB/CIFS 、 NFS 或雙（ SMB/NFS ）通訊協定存取磁碟區。
+
請填寫下列欄位、以設定對磁碟區的檔案存取。

+
.... * NFS 匯出原則 * ：提供下列詳細資料以提供 NFS 存取：
+
..... * 存取控制 * ：從下拉式功能表中選取 * 自訂匯出原則 * 、 * 現有匯出原則 * 或 * 無法存取 Volume * 。
..... * 匯出原則名稱 * ：
+
如果您選取自訂匯出原則、請從下拉式功能表中選取現有的原則名稱。

+
如果您選取現有的匯出原則、請輸入新的原則名稱。

..... * 新增匯出原則規則 * ：您也可以針對自訂匯出原則新增匯出原則規則至原則。


.... *SMB/CIFS 分享*：提供以下內容：
+
..... *名稱*：輸入 SMB/CIFS 共享名稱以提供存取權限。
..... *路徑*：使用預設磁碟區名定義路徑或提供內部目錄的共用。
+
卷名的有效路徑輸入（例如“avocado”）如下：

+
****** /酪梨
****** /酪梨/文件夾
****** /酪梨/資料夾/子資料夾
****** /酪梨/檔案名
+
共享名稱的有效路徑輸入（例如“伺服器”）如下：

****** \\伺服器
****** \\伺服器\項目
****** \\伺服器\專案\共享資源


..... * 權限 * ：選取 [ 完全控制 ] ， [ 讀取 / 寫入 ] ， [ 讀取 ] 或 [ 無存取權 ] ，然後輸入以分號（ ; ）分隔的使用者或群組。使用者或群組區分大小寫，使用者的網域必須使用「網域 \ 使用者名稱」格式。


.... * 安全樣式 * ：對於雙協議卷，請選擇 UNIX 或 NTFS 安全樣式。UNIX 是雙協定磁碟區的預設安全樣式。有關此上下文中用戶映射的詳細指導，請參閱 AWS 博客文章link:https://aws.amazon.com/blogs/storage/enabling-multiprotocol-workloads-with-amazon-fsx-for-netapp-ontap["使用 Amazon FSX for NetApp ONTAP 啟用多重傳輸協定工作負載"^]。


*** * 區塊存取 * ：允許執行關鍵業務應用程式的主機使用 iSCSI 傳輸協定存取磁碟區。區塊存取僅在檔案系統橫向擴充部署具有六個或更少 HA 配對時可用。
+
請填寫下列欄位、以設定對磁碟區的區塊存取。

+
.... *iSCSI 組態 * ：提供下列詳細資料、以設定 iSCSI 以進行磁碟區的區塊存取。
+
..... 選取 * 建立新的啟動器群組 * 或 * 對應現有的啟動器群組 * 。
..... 從下拉式功能表中選取 * 主機作業系統 * 。
..... 輸入新啟動器群組的 * 啟動器群組名稱 * 。
..... 在主機啟動器下、新增一或多個 iSCSI 合格名稱（ IQN ）主機啟動器。








. 在效率與保護之下、提供下列詳細資料：
+
.. *儲存效率*：預設啟用。選擇此項目可停用該功能。
+
ONTAP 使用重複資料刪除和壓縮功能實現儲存效率。重複資料刪除技術可消除重複的資料區塊資料壓縮會壓縮資料區塊、以減少所需的實體儲存容量。

.. * Snapshot polic*: 選擇快照策略以指定快照的頻率和保留。
+
以下是 AWS 的預設原則。對於自訂快照策略，您必須link:link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["建立連結的關聯"] 。

+
`default`:: 此原則會根據下列排程自動建立快照、並刪除最舊的快照複本、以便為較新的複本提供空間：
+
--
*** 每小時最多六個快照、每小時五分鐘拍攝一次。
*** 每週一至週六、午夜後 10 分鐘、最多可拍攝兩個每日快照。
*** 每個星期日午夜後 15 分鐘、最多拍攝兩個每週快照。
+

NOTE: 快照時間以檔案系統的時區為基礎、其預設為協調世界時間（ UTC ）。如需變更時區的相關資訊、請參閱 link:https://library.netapp.com/ecmdocs/ECMP1155684/html/GUID-E26E4C94-DF74-4E31-A6E8-1D2D2287A9A1.html["顯示及設定系統時區"^] NetApp 支援文件中的。



--
`default-1weekly`:: 此原則的運作方式與原則相同、 `default` 只是它只會從每週排程中保留一個快照。
`none`:: 此原則不會擷取任何快照。您可以將此原則指派給磁碟區、以防止自動擷取快照。


.. * 分層原則 * ：選取儲存在磁碟區中資料的分層原則。
+
平衡（自動） _ 是使用工作負載原廠主控台建立 Volume 時的預設分層原則。如需磁碟區分層原則的詳細資訊、請參閱 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Volume 儲存容量"^] AWS FSX for NetApp ONTAP 文件中的。請注意，工作負載工廠會在工作負載原廠主控台中使用以使用案例為基礎的名稱來分層原則，並在括弧中包含適用於 ONTAP 分層原則名稱的 FSX 。

.. * 可匯入的檔案 * ：此功能（也稱為 SnapLock ）預設為停用。啟用不可變檔案可防止在一定時期內刪除或覆蓋資料。只有在磁碟區建立期間，才能啟用此功能。啟用此功能後，便無法停用此功能。這是適用於 ONTAP 的 FSX 的優質功能，需要額外付費。如需詳細資訊，請參閱 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/how-snaplock-works.html["SnapLock 的運作方式"^]Amazon FSX for NetApp ONTAP 文件中的。
+
啟用「不可變檔案」功能會將此磁碟區中的檔案永久認可為不可變的 WORM （一次寫入多次讀取）狀態。

+
保留模式:: 您可以選擇兩種保留模式： _ 企業 _ 或 _ 法規遵循 _ 。
+
--
*** 在 _Enterprise_ 模式中，不可變的檔案或 SnapLock ，管理員可以在檔案保留期間刪除檔案。
*** 在 _ Compliance _ 模式中， WORM 檔案無法在其保留期限到期之前刪除。同樣地，在磁碟區內所有檔案的保留期間到期之前，無法刪除不可變的磁碟區。


--
保留期間:: 保留期間有兩種設定： _ 保留原則 _ 和 _ 保留期間 _ 。_ 保留原則 _ 定義在不可變 WORM 狀態下保留檔案的時間長度。您可以指定自己的保留原則，或使用預設保留原則（未指定），即 30 年。最小和最大保留期間 _ 定義鎖定檔案所允許的時間範圍。
+
--
附註:: 即使在保留期限到期之後，您仍無法修改 WORM 檔案。您只能刪除或設定新的保留期間，才能再次開啟 WORM 保護。


--
AUTOCOMMIT:: 您可以選擇啟用自動認可功能。如果檔案在自動認可期間內未變更，則自動認可功能會將檔案提交至 SnapLock 磁碟區的 WORM 狀態。自動提交功能預設為停用。您必須確保要自動提交的文件位於 SnapLock 磁碟區上。
Volume 附加模式:: 您無法修改受 WORM 保護檔案中的現有資料。不過，不可變的檔案可讓您使用 WORM 可擴充檔案來維護現有資料的保護。例如，您可以產生記錄檔，或是保留音訊或視訊串流資料，同時逐步將資料寫入記錄檔。link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/worm-state.html#worm-state-append["深入瞭解 Volume 附加模式"^]Amazon FSX for NetApp ONTAP 文件。
+
--
.不可變檔案的步驟
... 選取以啟用 * 由 SnapLock * 提供的可匯入檔案。
... 選取方塊以同意並繼續。
... 選取 * 啟用 * 。
... * 保留模式 * ：選擇 * 企業 * 或 * 法規遵循 * 模式。
... * 保留期間 * ：
+
**** 選取保留原則：
+
***** * 未指定 * ：將保留政策設為 30 年。
***** * 指定期間 * ：輸入設定您自己的保留原則所需的秒數，分鐘數，小時數，天，月數或年數。


**** 選擇最小和最大保留期間：
+
***** * 最小 * ：輸入秒數，分鐘數，小時數，天數，月數或年數，以設定最小保留期。
***** * 最大 * ：輸入秒數，分鐘數，小時數，天數，月數或年數，以設定最大保留期。




... *AUTOCOMMIT* ：禁用或啓用自動提交。如果啟用自動提交，請設定自動提交期間。
... * Volume 附加模式 * ：停用或啟用。可讓您將新內容新增至 WORM 檔案。


--


.. *ARP/AI*：當連結與檔案系統關聯時，NetApp 自主勒索軟體保護與 AI (ARP/AI) 預設為啟用。link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["了解有關 ARP/AI 的更多信息"]。接受聲明以繼續。
+
如果該功能不可用，則可能是由於以下原因之一：

+
*** 連結與檔案系統無關聯。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何關聯現有連結或建立並關聯新連結"]。連結建立關聯後，請返回此作業。
*** ARP/AI 不支援具有不可變檔案的磁碟區以及具有 iSCSI 和 NVMe 協定的磁碟區。
*** 檔案系統已具有 ARP/AI 策略。




. 在進階組態下、提供下列項目：
+
.. * 交會路徑 * ：在儲存 VM 的命名空間中輸入裝入磁碟區的位置。預設交會路徑為 `/<volume-name>`。
.. * 集合體清單 * ：僅適用於 FlexGroup Volume 。新增或移除集合體。集合體的最小數量為 1 。
.. * 組成數量 * ：僅適用於 FlexGroup Volume 。輸入每個 Aggregate 的組成數量。每個成分需要 100 GiB 。


. 選擇* Create *（建立*）。


.結果
工作負載工廠啟動卷創建。建立完成後，系統會在「磁碟區」標籤中顯示新磁碟區。
