---
sidebar: sidebar 
permalink: create-link.html 
keywords: links, add, add links, add link, create link 
summary: 您可以建立和管理連結、在 Workload Factory 帳戶和 ONTAP 檔案系統的一或多個 FSX 之間提供信任關係和連線能力。 
---
= 建立連結
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
您可以建立和管理連結、在 Workload Factory 帳戶和 ONTAP 檔案系統的一或多個 FSX 之間提供信任關係和連線能力。這可讓您直接從適用於 ONTAP 檔案系統的 FSX 監控及管理某些功能、這些功能無法透過 AWS FSX for ONTAP API 取得。

link:links-overview.html["深入瞭解連結"]。

.關於這項工作
連結利用 AWS Lambda 執行程式碼來回應事件、並自動管理該程式碼所需的運算資源。您建立的連結是 NetApp 帳戶的一部分、它們與 AWS 帳戶相關聯。

定義 ONTAP 檔案系統的 FSX 時、您可以在帳戶中建立連結。該連結將用於該檔案系統、其他的 FSX 可用於 ONTAP 檔案系統。

您必須在 AWS 帳戶中啟動 AWS CloudForgation 堆疊、才能建立連結。

.開始之前
* 您必須擁有認證才能登入 AWS 帳戶。
* 使用 CloudFormation 堆疊新增連結時、 AWS 帳戶必須具有下列權限：
+
[%collapsible]
====
[source, json]
----
"cloudformation:GetTemplateSummary",
"cloudformation:CreateStack",
"cloudformation:DeleteStack",
"cloudformation:DescribeStacks",
"cloudformation:ListStacks",
"cloudformation:DescribeStackEvents",
"cloudformation:ListStackResources",
"ec2:DescribeSubnets",
"ec2:DescribeSecurityGroups",
"ec2:DescribeVpcs",
"iam:ListRoles",
"iam:GetRolePolicy",
"iam:GetRole",
"iam:DeleteRolePolicy",
"iam:CreateRole",
"iam:DetachRolePolicy",
"iam:PassRole",
"iam:PutRolePolicy",
"iam:DeleteRole",
"iam:AttachRolePolicy",
"lambda:AddPermission",
"lambda:RemovePermission",
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:CreateFunction",
"lambda:DeleteFunction",
"lambda:TagResource",
"codestar-connections:GetSyncConfiguration",
"ecr:BatchGetImage",
"ecr:GetDownloadUrlForLayer"
----
====


.步驟
. 登入 link:https://console.workloads.netapp.com/["Workload Factory 主控台"^]
. 在儲存設備中、選取 * 移至儲存設備詳細目錄 * 。
. 在 *FSX for ONTAP * 標籤中、選取檔案系統的三點功能表以建立連結的關聯、然後選取 * 管理 * 。
. 在檔案系統總覽中、選取 * 關聯連結 * 。
. 在關聯連結對話方塊中、選取 * 建立新連結 * 、然後選取 * 繼續 * 。
. 在「建立連結」頁面上、提供下列項目：
+
.. * 連結名稱 * ：輸入您要用於此連結的名稱。名稱在您的帳戶中必須是唯一的。
.. * 標記 * ：您也可以選擇新增任何標記來與此連結建立關聯、以便更輕鬆地將資源分類。例如、您可以新增一個標記、將此連結識別為由 FSX 用於 ONTAP 檔案系統。
+
AWS 帳戶和帳戶、位置和安全性群組的其他資訊會根據 ONTAP 檔案系統的 FSX 自動擷取。



. 選取 * 重新導向至 CloudForgi狀態 * 。
+
隨即會顯示一個對話方塊、說明如何從 AWS CloudForgation 服務建立連結。

. 選取 * 繼續 * 以開啟 AWS 管理主控台、然後登入此 ONTAP 檔案系統的 AWS 帳戶。
. 在「快速建立堆疊」頁面的「功能」下、選取 * 我瞭解 AWS CloudForgation 可能會建立 IAM 資源 * 。
+
請注意、當您啟動 CloudForgation 範本時、 Lambda 會獲得三個權限。Workload Factory 在使用連結時會使用這些權限。

+
[source, json]
----
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:UpdateFunctionCode"
----
. 選取 * 建立堆疊 * 、然後選取 * 繼續 * 。
+
您可以從「事件」頁面監控連結建立狀態。這不應超過 5 分鐘。

. 返回 Workload Factory 介面、您會看到連結與 ONTAP 檔案系統的 FSX 相關聯。


.結果
您建立的連結會與適用於 ONTAP 檔案系統的 FSX 相關聯。
