---
sidebar: sidebar 
permalink: create-replication.html 
keywords: replication, replicate 
summary: 為適用於 ONTAP 檔案系統的 FSX 建立複寫關係、以避免在發生無法預見的災難時遺失資料。 
---
= 在 BlueXP  工作負載工廠建立複寫關係
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
在 BlueXP  工作負載工廠中為適用於 ONTAP 檔案系統的 FSX 建立複寫關係，以避免發生無法預見的災難時發生資料遺失。

.關於這項工作
複寫是新增的資料保護層、在資料所在的區域發生災難時、這是不可或缺的。如果您使用跨區域複寫、則可避免資料遺失。

此作業會為適用於 ONTAP 檔案系統的 FSX 中的一或所有來源磁碟區建立複寫關係。

目標檔案系統中的複寫磁碟區為資料保護（ DP ）磁碟區，並遵循命名格式： `{OriginalVolumeName}_copy`。

.開始之前
開始之前、請確定您符合下列先決條件。

* 您的儲存設備庫存中必須有兩個可用的檔案系統、才能建立複寫關係。
* 您用於複寫關係的兩個檔案系統必須有相關的連結。如果檔案系統沒有現有的連結，請參閱 link:create-link.html["首先建立連結"]。link:manage-links.html["建立連結的關聯"]在檔案系統中，在 * 帳戶名稱 * 下選擇 * 關聯連結 * 。連結在兩個檔案系統中建立關聯後、請返回此作業。


請完成下列步驟來複寫選取的磁碟區，或複寫檔案系統中的所有磁碟區。

您可以複寫一個來源（讀取 / 寫入）磁碟區或一個資料保護（ DP ）磁碟區。支援串聯複寫，但不支援第三個躍點。深入瞭解 link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_cascade-replication/cascade-replication.html["串聯複寫"^]。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在儲存設備中、選取 * 移至儲存設備詳細目錄 * 。
. 在 *FSX for ONTAP * 標籤中，選取包含要複寫之磁碟區的檔案系統三點功能表，然後選取 * 管理 * 。
. 可複寫檔案系統中的所有磁碟區，或複寫選取的磁碟區。
+
** 若要複寫檔案系統中的所有磁碟區：從檔案系統總覽選取 * 複寫資料 * 。
** 若要複寫選取的磁碟區：從檔案系統總覽中選取 * Volumes （磁碟區） * 標籤。
+
在 Volumes （卷）表中，選擇一個或多個卷，然後選擇 *Replicate data* 。



. 在「複寫資料」頁面的「複寫目標」下，提供下列項目：
+
.. * 適用於 ONTAP 檔案系統 * 的 FSX ：針對適用於 ONTAP 檔案系統的目標 FSX 、選取 ONTAP 檔案系統名稱的認證、區域和 FSX 。
.. * 儲存 VM 名稱 * ：從下拉式功能表中選取儲存 VM 。
.. *Volume name* ：目標 Volume 名稱會自動以下列格式產生 `{OriginalVolumeName}_copy`。您可以使用自動產生的 Volume 名稱或輸入其他 Volume 名稱。
.. * 使用案例 * ：選取下列其中一個複寫使用案例。視所選的使用案例而定，工作負載工廠會根據最佳實務做法，以建議的值填入表單。您可以接受建議的值，或在完成表單時進行變更。
+
*** 移轉：將資料傳輸至 ONTAP 檔案系統的目標 FSX
*** 熱災難恢復：確保關鍵工作負載的高可用度和快速災難恢復
*** 冷災難恢復或歸檔災難恢復：
+
**** 冷災難恢復：使用較長的恢復時間目標（ RTO ）和恢復點物件（ RPO ）來降低成本
**** 歸檔：複寫資料以供長期儲存和法規遵循


*** 其他
+
此外，使用案例選項會決定複寫原則或 SnapMirror 原則（ ONTAP ）。用於描述複寫原則的術語來自link:https://docs.netapp.com/us-en/ontap/data-protection/default-protection-policies-concept.html["部分9文件ONTAP"^]。

+
**** 對於移轉和其他作業，複寫原則稱為 _MirrorAllSnapshots_ 。_MirrorAllSnapshots_ 是用於鏡射所有快照和最新作用中檔案系統的非同步原則。
**** 對於熱災難恢復，冷災難恢復或歸檔災難恢復，複製策略稱爲 _MirrorAndVault_ 。_MirrorAndVault_ 是一種非同步和資料保險箱原則，可用於鏡射最新的作用中檔案系統，以及每日和每週快照。
+
在所有使用案例中，如果您啟用快照以進行長期保留，則預設複寫原則為 _MirrorAndVault_ 。





.. * 分層原則 * ：選取儲存在目標 Volume 中的資料分層原則。分層原則預設為您所選使用案例的建議分層原則。
+
平衡（自動） _ 是使用工作負載原廠主控台建立 Volume 時的預設分層原則。如需磁碟區分層原則的詳細資訊、請參閱 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Volume 儲存容量"^] AWS FSX for NetApp ONTAP 文件中的。請注意，工作負載工廠會在工作負載原廠主控台中使用以使用案例為基礎的名稱來分層原則，並在括弧中包含適用於 ONTAP 分層原則名稱的 FSX 。

+
如果您選取移轉使用案例，工作負載工廠會自動選擇將來源 Volume 的分層原則複製到目標 Volume 。您可以取消選取以複製分層原則，並選取適用於所選複寫磁碟區的分層原則。

.. * 最大傳輸速率 * ：選取 * 受限 * 、然後以 MB/s 為單位輸入最大傳輸限制或者、選取 * 無限 * 。
+
如果沒有限制、網路和應用程式的效能可能會下降。或者、我們建議為 ONTAP 檔案系統的關鍵工作負載（例如主要用於災難恢復的工作負載）提供不限傳輸率的 FSX 。



. 在複寫設定下、提供下列項目：
+
.. * 複寫間隔 * ：選取快照從來源磁碟區傳輸到目標磁碟區的頻率。
.. * 長期保留 * ：可選擇啟用快照以進行長期保留。長期保留功能可讓業務服務持續運作、即使整個站台發生故障、也能支援應用程式使用次要複本以透明方式容錯移轉。
+
未啟用長期保留的複製將使用 _MirrorAllSnapshots_ 策略。啟用長期保留會將 _MirrorAndVault_ 策略指派給複製。

+
如果您啟用長期保留、請選取現有原則或建立新原則、以定義要複寫的快照和要保留的數量。

+

NOTE: 長期保留需要相符的來源和目標標籤。如有需要，工作負載工廠可能會為您建立遺失的標籤。

+
*** * 選擇現有的原則 * ：從下拉式功能表中選取現有的原則。
*** * 建立新原則 * ：提供下列項目：
+
**** * 原則名稱 * ：輸入原則名稱。
**** 選用：啟用不可變快照。
+
***** 選取 * 啟用不可變快照 * ，以防止在保留期間刪除在此原則中拍攝的快照。
***** 將 * 保留期間 * 設定為小時數，天數，月數或年數。


**** * Snapshot Policies * ：在表格中、選取快照原則頻率和要保留的複本數量。您可以選取多個快照原則。






. 選擇* Create *（建立*）。


.結果
複寫關係會出現在 ONTAP 檔案系統的目標 FSX 的 * 複寫關係 * 索引標籤中。
