---
sidebar: sidebar 
permalink: create-volume.html 
keywords: create volume, FSx for ONTAP volume 
summary: 為 ONTAP 檔案系統設定 FSX 之後、您可以為 ONTAP Volume 建立 FSX 。 
---
= 為 ONTAP Volume 建立 FSX
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
為 ONTAP 檔案系統設定 FSX 之後、您可以為 ONTAP Volume 建立 FSX 。

.關於這項工作
適用於 ONTAP Volume 的 FSX 是用於分組資料、判斷資料儲存方式、以及判斷資料存取類型的虛擬資源。Volume 不會消耗檔案系統儲存容量。儲存在磁碟區中的資料主要會消耗 SSD 儲存設備。視磁碟區的分層原則而定、資料可能也會佔用容量集區儲存空間。您可以在建立磁碟區時設定磁碟區的大小、稍後也可以變更其大小。

您的磁碟區可能會使用下列通訊協定：

* CIFS ：適用於 Windows 作業系統的檔案儲存傳輸協定
* NFS ：適用於 Unix 作業系統的檔案儲存傳輸協定
* iSCSI ：區塊儲存傳輸協定


.開始之前
建立 Volume 之前、請先檢閱下列先決條件：

* 您必須在 Workload Factory 中擁有適用於 ONTAP 檔案系統的 FSX 。
* 您必須擁有儲存 VM 。
* 若要存取傳輸協定、請完成下列步驟：
+
** 若要設定對磁碟區的存取權、您必須 link:manage-links.html["建立連結的關聯"]。如果您沒有現有的連結、 link:create-link.html["建立連結"]。若要在檔案系統中建立連結、請按一下 * 帳戶名稱 * 下的 * 關聯連結 * 。連結建立關聯後、請返回此作業。
** 您必須設定所選傳輸協定（ CIFS 、 NFS 或 iSCSI ）的存取權。




.步驟
. 登入 link:https://console.workloads.netapp.com/["Workload Factory 主控台"^]
. 在儲存設備中、選取 * 移至儲存設備詳細目錄 * 。
. 在 *FSX for ONTAP * 標籤中、選取您要在其中建立磁碟區的檔案系統三點功能表、然後選取 * 管理 * 。
. 在 * 概述 * 標籤中、按一下 * 建立 Volume * 。
. 在「一般詳細資料」下的「建立 Volume 」頁面上、提供下列詳細資料：
+
.. * Volume 名稱 * ：輸入磁碟區的名稱。
.. * 儲存 VM 名稱 * ：選擇性地輸入儲存 VM 名稱。
.. * Volume 樣式 * ：選擇 * FlexVol * 或 * FlexGroup * Volume 。
+
FlexVol Volume 樣式預設為選取。

+
FlexGroup Volume 大小取決於組成數量。每個成分需要 100 GiB 。

.. * Volume Size* ：輸入 Volume 大小和單位。
+
也可以啟用 Volume 自動擴充。當您選擇 * 檔案存取 * 作為磁碟區存取類型時、即可使用此選項。

.. * 標記 * ：您可以選擇性地新增最多 50 個標記。


. 在 Access （僅適用於具有相關連結的檔案系統）下、提供下列詳細資料：
+
.. * 存取類型 * ：選取 * 檔案存取 * 或 * 封鎖存取 * 。設定磁碟區存取的其他欄位會因您的選擇而異。
+
*** * 檔案存取 * ：允許多個授權使用者和裝置使用 SMB/CIFS 、 NFS 或雙（ SMB/NFS ）通訊協定存取磁碟區。
+
請填寫下列欄位、以設定對磁碟區的檔案存取。

+
.... * NFS 匯出原則 * ：提供下列詳細資料以提供 NFS 存取：
+
..... * 存取控制 * ：從下拉式功能表中選取 * 自訂匯出原則 * 、 * 現有匯出原則 * 或 * 無法存取 Volume * 。
..... * 匯出原則名稱 * ：
+
如果您選取自訂匯出原則、請從下拉式功能表中選取現有的原則名稱。

+
如果您選取現有的匯出原則、請輸入新的原則名稱。

..... * 新增匯出原則規則 * ：您也可以針對自訂匯出原則新增匯出原則規則至原則。


.... *CIFS 共享 * ：輸入 CIFS 共享名稱以提供 SMB 存取。


*** * 區塊存取 * ：允許執行關鍵業務應用程式的主機使用 iSCSI 傳輸協定存取磁碟區。
+
請填寫下列欄位、以設定對磁碟區的區塊存取。

+
.... *iSCSI 組態 * ：提供下列詳細資料、以設定 iSCSI 以進行磁碟區的區塊存取。
+
..... 選取 * 建立新的啟動器群組 * 或 * 對應現有的啟動器群組 * 。
..... 從下拉式功能表中選取 * 主機作業系統 * 。
..... 輸入新啟動器群組的 * 啟動器群組名稱 * 。
..... 在主機啟動器下、新增一或多個 iSCSI 合格名稱（ IQN ）主機啟動器。








. 在效率與保護之下、提供下列詳細資料：
+
.. * 儲存效率 * ：停用或啟用儲存效率。
+
利用 ONTAP 的重複資料刪除和壓縮功能、即可提高儲存效率。重複資料刪除技術可消除重複的資料區塊資料壓縮會壓縮資料區塊、以減少所需的實體儲存容量。

.. * Snapshot polic*: 選擇快照策略以指定快照的頻率和保留。
+
以下是 AWS 的預設原則。對於自訂快照原則、您必須建立連結的關聯。

+
`default`:: 此原則會根據下列排程自動建立快照、並刪除最舊的快照複本、以便為較新的複本提供空間：
+
--
*** 每小時最多六個快照、每小時五分鐘拍攝一次。
*** 每週一至週六、午夜後 10 分鐘、最多可拍攝兩個每日快照。
*** 每個星期日午夜後 15 分鐘、最多拍攝兩個每週快照。
+

NOTE: 快照時間以檔案系統的時區為基礎、其預設為協調世界時間（ UTC ）。如需變更時區的相關資訊、請參閱 link:https://library.netapp.com/ecmdocs/ECMP1155684/html/GUID-E26E4C94-DF74-4E31-A6E8-1D2D2287A9A1.html["顯示及設定系統時區"^] NetApp 支援文件中的。



--
`default-1weekly`:: 此原則的運作方式與原則相同、 `default` 只是它只會從每週排程中保留一個快照。
`none`:: 此原則不會擷取任何快照。您可以將此原則指派給磁碟區、以防止自動擷取快照。


.. * 分層原則 * ：選取儲存在磁碟區中資料的分層原則。
+
Auto 是使用使用者介面建立磁碟區時的預設分層原則。如需磁碟區分層原則的詳細資訊、請參閱 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Volume 儲存容量"^] AWS FSX for NetApp ONTAP 文件中的。



. 在進階組態下、提供下列項目：
+
.. * 交會路徑 * ：在儲存 VM 的命名空間中輸入裝入磁碟區的位置。預設交會路徑為 `/<volume-name>`。
.. * 集合體清單 * ：僅適用於 FlexGroup Volume 。新增或移除集合體。集合體的最小數量為 1 。
.. * 組成數量 * ：僅適用於 FlexGroup Volume 。輸入每個 Aggregate 的組成數量。每個成分需要 100 GiB 。


. 按一下「 * 建立 * 」。


.結果
磁碟區建立已啟動。建立後、新的 Volume 就會出現在 Volumes （磁碟區）標籤中。
