---
sidebar: sidebar 
permalink: create-file-system.html 
keywords: create, FSx file system, ONTAP file system, workload factory, storage 
summary: 使用 BlueXP  工作負載工廠，您可以為 ONTAP 檔案系統建立 FSX ，以新增及管理磁碟區和其他資料服務。 
---
= 在 BlueXP  工作負載工廠中為 ONTAP 檔案系統建立 FSX
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
使用 BlueXP  工作負載工廠，您可以為 ONTAP 檔案系統建立 FSX ，以新增及管理磁碟區和其他資料服務。

.關於這項工作
儲存 VM 和安全性群組是建立檔案系統的一部分。

.開始之前
在為 ONTAP 檔案系統建立 FSX 之前、您需要：

* IAM 角色的 ARN ，賦予工作負載工廠為 ONTAP 檔案系統建立 FSX 所需的權限。link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["瞭解如何授予 AWS 帳戶權限"^]。
* 您將在其中建立FSX以利ONTAP 執行個體的區域和VPC資訊。




== 為 ONTAP 檔案系統建立 FSX

您可以使用 _Quick creity_ 或 _Advanced creity_ 、為 ONTAP 檔案系統建立 FSX 。您也可以使用 Codebox 中的下列工具： REST API 、 CloudForformation 和 Terraform 。link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["瞭解如何使用 Codebox 進行自動化"^]。


NOTE: 從 Codebox 使用 Terraform 時、您複製或下載的程式碼會隱藏 `fsxadmin` 和 `vsadmin` 密碼。執行程式碼時、您需要重新輸入密碼。

[role="tabbed-block"]
====
.快速建立
--
快速建立可讓您使用建議的最佳實務組態。您可以在為 ONTAP 檔案系統建立 FSX 之後、變更大部分的設定。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在儲存設備中、選取 * 為 ONTAP * 建立 FSX 。
. 在 Create FSX for （為 ONTAP 建立 FSX ）頁面上、選取 * Quick create* （快速建立 * ）。
+
您也可以載入儲存的組態。

. 在「檔案系統一般組態」下、提供下列項目：
+
.. * AWS 認證 * ：選取以在工作負載工廠中新增 AWS 認證，或在沒有認證的情況下繼續。
.. * 檔案系統名稱 * ：輸入檔案系統的名稱。
.. * 部署拓撲 * ：選擇部署拓撲。
+
*** 橫向擴充拓撲是指使用一個檔案系統來進行資料發佈、並可增加規模以因應資料增長。
*** 橫向擴充拓撲是指用於資料發佈的多個檔案系統。


.. * HA 配對 * ：輸入 HA 配對數。
+
*** 對於橫向擴充部署、您只能有一個 HA 配對。
*** 對於橫向擴充部署、您可以有兩對到十二對 HA 。
+
若要在檔案系統上佈建 iSCSI 區塊磁碟區，請選取不超過六個 HA 配對。



.. * 部署類型 * ：選擇部署類型。
+
*** 單一可用性區域（單一 AZ ）部署：監控硬體故障並在發生故障時自動更換基礎架構元件，藉此提供可用度。在可用性區域內自動複寫資料、以保護資料免於元件故障、進而達到高耐用度。
*** 多個可用性區域（ Multi-AZ ）部署：即使可用性區域不可用、仍可持續提供資料可用度。多 AZ 檔案系統支援單一 AZ 檔案系統的所有可用度與耐用度功能。多 AZ 檔案系統是專為業務關鍵的正式作業工作負載所設計、這些工作負載需要高可用度的共享 ONTAP 檔案資料、而且需要跨可用性區域內建複寫的儲存設備。


.. * 標記 * ：您可以選擇性地新增最多 50 個標記。


. 在 * 網路與安全 * 下的 * 區域與 VPC* 欄位中、選取檔案系統的區域和 VPC 。
. 在 * 檔案系統詳細資料 * 下、提供下列資訊：
+
.. * SSD 儲存容量 * ：輸入儲存容量並選擇儲存容量單位。
.. * ONTAP 認證 * ：輸入您的 ONTAP 使用者名稱和密碼。
.. *SMB/CIFS 設定 * ：選用。如果您打算使用 SMB/CIFS 通訊協定來存取磁碟區、則必須在建立檔案系統時、為儲存 VM 設定 Active Directory 。針對為此檔案系統建立的儲存 VM 、提供下列詳細資料。
+
... * 要加入的 Active Directory 網域 * ：輸入 Active Directory 的完整網域名稱（ FQDN ）。
... * DNS IP 位址 * ：輸入最多三個 DNS IP 位址、並以逗號分隔。
... *SMB 伺服器 NetBIOS 名稱 * ：輸入 Active Directory 電腦物件的 SMB 伺服器 NetBIOS 名稱、以建立儲存 VM 。這是 Active Directory 中此儲存 VM 的名稱。
... * 使用者名稱 * ：在現有的 Active Directory 中輸入服務帳戶的使用者名稱。
+
請勿包含網域首碼或尾碼。對於 `EXAMPLE\ADMIN`，請使用 `ADMIN`。

... * 密碼 * ：輸入服務帳戶的密碼。
... * 組織單位 * ：您也可以輸入組織單位的名稱、以便在其中為 ONTAP 的 FSX 建立電腦帳戶。OU 是您要加入檔案系統之組織單位的辨別路徑名稱。
... * 委派系統管理員群組 * ：您也可以在 Active Directory 中輸入可管理檔案系統的群組名稱。
+
如果您使用的是 AWS 託管的 Microsoft AD 、則必須指定群組、例如 AWS 委派的 FSX 管理員、 AWS 委派管理員、或是具有 OU 委派權限的自訂群組。

+
如果您要加入自我管理的 AD 、請使用 AD 中的群組名稱。預設群組為 `Domain Admins`。





. 開啟 * 摘要 * 以檢閱您定義的組態。如果需要、您可以在此時變更任何設定、然後再儲存或建立檔案系統。
. 儲存或建立檔案系統。


如果您建立檔案系統、現在可以在 * 庫存 * 頁面中檢視 ONTAP 檔案系統的 FSX 。

--
.進階建立
--
使用 Advanced create 、您可以設定所有組態選項、包括可用度、安全性、備份和維護。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在儲存設備中、選取 * 為 ONTAP * 建立 FSX 。
. 在 Create FSX for （為 ONTAP 建立 FSX ）頁面上、選取 * Advanced create* （進階建立 * ）。
+
您也可以載入儲存的組態。

. 在「檔案系統一般組態」下、提供下列項目：
+
.. * AWS 認證 * ：選取以在工作負載工廠中新增 AWS 認證，或在沒有認證的情況下繼續。
.. * 檔案系統名稱 * ：輸入檔案系統的名稱。
.. * 部署拓撲 * ：選擇部署拓撲。
+
*** 橫向擴充拓撲是指使用一個檔案系統來進行資料發佈、並可增加規模以因應資料增長。
*** 橫向擴充拓撲是指用於資料發佈的多個檔案系統。


.. * HA 配對 * ：輸入 HA 配對數。
+
*** 對於橫向擴充部署、您只能有一個 HA 配對。
*** 對於橫向擴充部署、您可以有兩對到十二對 HA 。
+
若要在檔案系統上佈建 iSCSI 區塊磁碟區，請選取不超過 6 個 HA 配對。



.. * 部署類型 * ：選擇部署類型。
+
*** 單一可用性區域（單一 AZ ）部署：監控硬體故障並在發生故障時自動更換基礎架構元件，藉此提供可用度。在可用性區域內自動複寫資料、以保護資料免於元件故障、進而達到高耐用度。
*** 多個可用性區域（ Multi-AZ ）部署：即使可用性區域不可用、仍可持續提供資料可用度。多 AZ 檔案系統支援單一 AZ 檔案系統的所有可用度與耐用度功能。多 AZ 檔案系統是專為業務關鍵的正式作業工作負載所設計、這些工作負載需要高可用度的共享 ONTAP 檔案資料、而且需要跨可用性區域內建複寫的儲存設備。


.. * 標記 * ：您可以選擇性地新增最多 50 個標記。


. 在「網路與安全性」下、提供下列項目：
+
.. * 區域與 VPC* ：選取檔案系統的區域與 VPC 。
.. * 安全性群組 * ：建立或使用現有的安全性群組。
+
如需新的安全性群組，請參閱<<安全性群組詳細資料,安全性群組詳細資料>>以取得安全性群組通訊協定，連接埠和角色的說明。

.. * 可用性區域 * ：選取可用性區域和子網路。
+
*** 對於叢集組態節點 1 ：選取可用區域和子網路。
*** 對於叢集組態節點 2 ：選取可用區域和子網路。


.. *VPC 路由表 * ：選擇 VPC 路由表以允許用戶端存取磁碟區。
.. * 端點 IP 位址範圍 * ：選取 * VPC* 以外的浮動 IP 位址範圍、或 * 輸入 IP 位址範圍 * 並輸入 IP 位址範圍。
.. * 加密 * ：從下拉式清單中選取加密金鑰名稱。


. 在「檔案系統詳細資料」下、提供下列資訊：
+
.. * SSD 儲存容量 * ：輸入儲存容量並選擇儲存容量單位。
.. * 已配置的 IOPS * ：選擇 * 自動 * 或 * 使用者已配置 * 。
.. * 每個 HA 配對的處理量容量 * ：每個 HA 配對的選取處理量容量。
.. * ONTAP 認證 * ：輸入您的 ONTAP 使用者名稱和密碼。
.. * 儲存 VM 認證 * ：輸入您的使用者名稱。密碼可能是此檔案系統所特有的、或者您也可以使用為 ONTAP 認證輸入的相同密碼。
.. *SMB/CIFS 設定 * ：選用。如果您打算使用 SMB/CIFS 通訊協定來存取磁碟區、則必須在建立檔案系統時、為儲存 VM 設定 Active Directory 。針對為此檔案系統建立的儲存 VM 、提供下列詳細資料。
+
... * 要加入的 Active Directory 網域 * ：輸入 Active Directory 的完整網域名稱（ FQDN ）。
... * DNS IP 位址 * ：輸入最多三個 DNS IP 位址、並以逗號分隔。
... *SMB 伺服器 NetBIOS 名稱 * ：輸入 Active Directory 電腦物件的 SMB 伺服器 NetBIOS 名稱、以建立儲存 VM 。這是 Active Directory 中此儲存 VM 的名稱。
... * 使用者名稱 * ：在現有的 Active Directory 中輸入服務帳戶的使用者名稱。
+
請勿包含網域首碼或尾碼。對於 `EXAMPLE\ADMIN`，請使用 `ADMIN`。

... * 密碼 * ：輸入服務帳戶的密碼。
... * 組織單位 * ：您也可以輸入組織單位的名稱、以便在其中為 ONTAP 的 FSX 建立電腦帳戶。OU 是您要加入檔案系統之組織單位的辨別路徑名稱。
... * 委派系統管理員群組 * ：您也可以在 Active Directory 中輸入可管理檔案系統的群組名稱。
+
如果您使用的是 AWS 託管的 Microsoft AD 、則必須指定群組、例如 AWS 委派的 FSX 管理員、 AWS 委派管理員、或是具有 OU 委派權限的自訂群組。

+
如果您要加入自我管理的 AD 、請使用 AD 中的群組名稱。預設群組為 `Domain Admins`。





. 在「備份與維護」下、提供下列項目：
+
.. *FSX for ONTAP Backup* ：預設會啟用每日自動備份。視需要停用。
+
... * 自動備份保留期間 * ：輸入保留自動備份的天數。
... * 每日自動備份時段 * ：選擇 * 無偏好設定 * （為您選擇每日備份開始時間）或 * 選擇每日備份開始時間 * 、並指定開始時間。
... * 每週維護時段 * ：選擇 * 無偏好設定 * （為您選擇每週維護時段開始時間）或 * 選擇每週 30 分鐘維護時段的開始時間 * 、並指定開始時間。




. 儲存或建立檔案系統。


如果您建立檔案系統、現在可以在 * 庫存 * 頁面中檢視 ONTAP 檔案系統的 FSX 。

--
====


== 安全性群組詳細資料

下表提供安全性群組的詳細資料，包括通訊協定，連接埠和角色。

[]
====
[cols="2,2,4a"]
|===
| 傳輸協定 | 連接埠 | 角色 


| SSH | 22  a| 
SSH 存取叢集管理 LIF 的 IP 位址或節點管理 LIF



| TCP | 80  a| 
網頁存取叢集管理 LIF 的 IP 位址



| TCP/UDP | 111  a| 
遠端程序需要 NFS



| TCP/UDP | 135  a| 
遠端程序需要 CIFS



| UDP | 137  a| 
CIFS 的 NetBIOS 名稱解析



| TCP/UDP | 139  a| 
CIFS 的 NetBios 服務工作階段



| TCP | 443  a| 
ONTAP REST API 存取叢集管理 LIF 或 SVM 管理 LIF 的 IP 位址



| TCP | 445  a| 
Microsoft SMB/CIFS over TCP 搭配 NetBios 架構



| TCP/UDP | 635  a| 
NFS 掛載



| TCP | 749  a| 
Kerberos



| TCP/UDP | 2049  a| 
NFS 伺服器精靈



| TCP | 3260  a| 
透過 iSCSI 資料 LIF 存取 iSCSI



| TCP/UDP | 4045  a| 
NFS 鎖定精靈



| TCP/UDP | 4046  a| 
NFS 的網路狀態監控



| UDP | 4049  a| 
NFS 配額傳輸協定



| TCP | 10000  a| 
網路資料管理傳輸協定（ NDMP ）和 NetApp SnapMirror 叢集間通訊



| TCP | 11104  a| 
管理 NetApp SnapMirror 叢集間通訊



| TCP | 11105  a| 
使用叢集間生命體進行 SnapMirror 資料傳輸



| TCP/UDP | 161-162  a| 
簡易網路管理傳輸協定（ SNMP ）



| 所有 ICMP | 全部  a| 
Ping 執行個體

|===
====
.下一步
您可以在儲存設備庫存中使用檔案系統 link:create-volume.html["建立 Volume"]、管理適用於 ONTAP 檔案系統的 FSX 、以及設定 link:data-protection-overview.html["資料保護"] 資源。
