---
sidebar: sidebar 
permalink: create-storage-vm.html 
keywords: create storage VM, create svm 
summary: '您可以建立 FSx for ONTAP儲存虛擬機器 (SVM)，為NetApp Workload Factory 中的工作負載提供儲存和資料服務。' 
---
= 為 ONTAP 檔案系統的 FSX 建立儲存 VM
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
為 FSx for ONTAP檔案系統建立儲存虛擬機器 (SVM)，以虛擬方式存取NetApp Workload Factory 中工作負載的儲存和資料服務。

.關於這項工作
儲存虛擬機器是獨立的檔案伺服器，您可以使用它來存取工作負載工廠儲存中每個工作負載的資料。每個 SVM 都有自己的管理憑證和端點，用於管理和存取資料。

有了 SVM 、當您存取適用於 ONTAP 的 FSX 中的資料時、您的用戶端和工作站會使用 SVM 的端點（ IP 位址）、掛載由 SVM 託管的 Volume 、 CIFS/SMB 共享區或 iSCSI LUN 。

.開始之前
確認每個檔案系統支援的儲存 VM 數量。如需每個檔案系統的 SVM 最大數量、請參閱 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["管理 ONTAP 儲存虛擬機器的 FSX"^] AWS 文件中的。



== 建立儲存VM

您可以從 Workload Factory 控制台建立儲存虛擬機器。您也可以使用 Codebox 中提供的以下工具：REST API、CloudFormation 和 Terraform。link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["瞭解如何使用 Codebox 進行自動化"^] 。


NOTE: 從 Codebox 使用 Terraform 時、您複製或下載的程式碼會隱藏 `fsxadmin` 和 `vsadmin` 密碼。執行程式碼時、您需要重新輸入密碼。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在儲存圖塊中，選擇*轉到儲存*。
. 從儲存選單中，選擇 *FSx for ONTAP*。
. 從 *FSx for ONTAP* 中選擇檔案系統的操作選單，然後選擇 *管理*。
. 在檔案系統概覽的「儲存虛擬機器」下，選擇「建立儲存虛擬機器」。
. 在「建立儲存虛擬機器」頁面的「儲存虛擬機器配置」下，提供以下資訊：
+
.. * 名稱 * ：輸入儲存 VM 的名稱。
.. * 儲存 VM 認證 * ：提供此儲存 VM 使用者的密碼 `vsadmin` 、或使用檔案系統的 `fsxadmin` 使用者認證。
.. * 根磁碟區安全樣式 * ：根據存取資料的用戶端類型、選取根磁碟區安全樣式： UNIX （ Linux 用戶端）、 NTFS （ Windows 用戶端）或混合。
.. * 標記 * ：您可以選擇性地新增最多 50 個標記。


. 選擇* Create *（建立*）。

