---
sidebar: sidebar 
permalink: create-link.html 
keywords: connect, connection, link, lambda link, associate link, create link, authenticate link 
summary: 您可以建立及管理連結，以在 BlueXP  工作負載工廠帳戶和一或多個適用於 ONTAP 檔案系統的 FSX 之間提供信任關係和連線能力。 
---
= 使用 Lambda 連結連線至適用於 ONTAP 檔案系統的 FSX
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
若要執行進階ONTAP管理操作，請在工作負載工廠帳戶和一個或多個 FSx for ONTAP檔案系統之間建立連線。這涉及關聯新的和現有的 Lambda 鏈接，並對鏈接進行驗證。透過連結關聯，您可以直接從 FSx for ONTAP檔案系統監控和管理某些無法透過Amazon FSx for ONTAP API 取得的功能。

link:links-overview.html["深入瞭解連結"]。

.關於這項工作
連結利用 AWS Lambda 執行程式碼來回應事件、並自動管理該程式碼所需的運算資源。您建立的連結是 NetApp 帳戶的一部分、它們與 AWS 帳戶相關聯。

您可以在定義 FSx for ONTAP檔案系統時在您的帳戶中建立連結。此連結用於該檔案系統，也可以用於其他 FSx for ONTAP檔案系統。您也可以稍後關聯檔案系統的連結。

連結需要驗證。您可以使用儲存在工作負載工廠憑證服務中的憑證或儲存在 AWS Secrets Manager 中的憑證來驗證連結。每個連結僅支援一種身份驗證方法。例如，如果您選擇使用 AWS Secrets Manager 進行連結驗證，則以後無法變更身份驗證方法。


NOTE: 使用 Connector 時不支援 AWS Secrets Manager 。



== 建立新連結的關聯

建立新連結的關聯包括連結建立和關聯。

在此工作流程中，您有兩個建立連結的選項 - 自動或手動。您必須在 AWS 帳戶中啟動 AWS CloudForgation 堆疊、才能建立連結。

* 自動：透過工作負載工廠建立自動註冊的連結。這需要用於工作負載工廠自動化的令牌，並且 CloudFormation 程式碼的生命週期很短，最多可使用六個小時。
* 手動：建立具有手動登錄的連結。CloudForgation 程式碼持續提供您更多時間來完成作業。這在與安全和 DevOps 等不同團隊合作時很有用，因為他們可能需要先授予完成連結建立所需的權限。


.開始之前
* 您應該考慮要使用哪個連結建立選項。
* 您必須在工作負載工廠中至少有一個適用於 ONTAP 檔案系統的 FSX 。若要發現或建立 FSx for ONTAP 檔案系統，您必須擁有一個具有 FSx for ONTAP 執行個體權限的 AWS 帳戶，且link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html#overview["在工作負載工廠新增認證"^]具有儲存管理的_唯讀_或_讀/寫_權限。
* 必須在與 FSx for ONTAP 檔案系統關聯的安全性群組中開啟下列連接埠以實現連結連線。
+
** 對於工作負載工廠控制台：連接埠 443 (HTTPS)
** 對於 CloudShell：連接埠 22 (SSH)


* 使用 CloudFormation 堆疊新增連結時、 AWS 帳戶必須具有下列權限：
+
[%collapsible]
====
[source, json]
----
"cloudformation:GetTemplateSummary",
"cloudformation:CreateStack",
"cloudformation:DeleteStack",
"cloudformation:DescribeStacks",
"cloudformation:ListStacks",
"cloudformation:DescribeStackEvents",
"cloudformation:ListStackResources",
"ec2:DescribeSubnets",
"ec2:DescribeSecurityGroups",
"ec2:DescribeVpcs",
"iam:ListRoles",
"iam:GetRolePolicy",
"iam:GetRole",
"iam:DeleteRolePolicy",
"iam:CreateRole",
"iam:DetachRolePolicy",
"iam:PassRole",
"iam:PutRolePolicy",
"iam:DeleteRole",
"iam:AttachRolePolicy",
"lambda:AddPermission",
"lambda:RemovePermission",
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:CreateFunction",
"lambda:DeleteFunction",
"lambda:TagResource",
"codestar-connections:GetSyncConfiguration",
"ecr:BatchGetImage",
"ecr:GetDownloadUrlForLayer"
----
====


[role="tabbed-block"]
====
.自動建立
--
使用 CloudForgation 在工作負載工廠內自動建立並註冊連結。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在儲存設備中、選取 * 移至儲存設備詳細目錄 * 。
. 在 *FSX for ONTAP * 標籤中，選取檔案系統的三點功能表以建立連結，然後選取 * 建立連結 * 。
. 在關聯連結對話方塊中、選取 * 建立新連結 * 、然後選取 * 繼續 * 。
. 在「建立連結」頁面上、提供下列項目：
+
.. * 連結名稱 * ：輸入您要用於此連結的名稱。名稱在您的帳戶中必須是唯一的。
.. * AWS Secrets Manager* ：選用。允許工作負載工廠從 AWS Secrets Manager 擷取適用於 ONTAP 存取認證的 FSX 。
+
連結部署堆疊會自動將以下預設金鑰管理器 ARN 正規表示式新增至 Lambda 權限策略： `arn:aws:secretsmanager:<link_deployment_region>:<link_deployment_account_id>:secret:FSxSecret*` 。

+
您可以根據預設權限建立機密，或為連結原則指派自訂權限。

+
* 將 VPC 私有端點設定為 AWS Secrets Manager* 預設為停用。選取此選項會使用 VPC 私有端點儲存機密，而非儲存在本機。

.. *連結權限*：選擇以下連結權限選項之一：
+
*** *自動*：選擇此選項，以便 AWS CloudFormation 程式碼自動建立 Lambda 權限原則和執行角色。
*** *使用者提供*：選擇此選項可將指定的 Lambda 執行角色及其附加的策略指派給 Lambda 連結。 Lambda需要以下權限。 `secretsmanager:GetSecretValue`僅當您啟用 AWS Secrets Manager 時才需要權限。
+
[source, json]
----
"ec2:CreateNetworkInterface",
"ec2:DescribeNetworkInterfaces",
"ec2:DeleteNetworkInterface",
"ec2:AssignPrivateIpAddresses",
"ec2:UnassignPrivateIpAddresses",
"secretsmanager:GetSecretValue"
----
+
在文字方塊中輸入 Lambda 執行角色 ARN。



.. * 標記 * ：您也可以選擇新增任何標記來與此連結建立關聯、以便更輕鬆地將資源分類。例如、您可以新增一個標記、將此連結識別為由 FSX 用於 ONTAP 檔案系統。
+
工作負載工廠根據 FSx for ONTAP檔案系統自動擷取 AWS 帳戶、位置和安全群組。



. 選擇* Create *（建立*）。
+
出現「重新導向到 CloudFormation」對話方塊並解釋如何從 AWS CloudFormation 服務建立連結。

. 選取 * 繼續 * 以開啟 AWS 管理主控台、然後登入此 ONTAP 檔案系統的 AWS 帳戶。
. 在「快速建立堆疊」頁面的「功能」下、選取 * 我瞭解 AWS CloudForgation 可能會建立 IAM 資源 * 。
+
請注意、當您啟動 CloudForgation 範本時、 Lambda 會獲得三個權限。工作負載工廠在使用連結時會使用這些權限。

+
[source, json]
----
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:UpdateFunctionCode"
----
. 選取 * 建立堆疊 * ，然後選取 * 繼續 * 。
+
您可以在事件頁面上監控連結建立狀態。這應該不會超過 5 分鐘。

. 返回工作負載原廠介面，您會看到連結與 ONTAP 檔案系統的 FSX 相關聯。


--
.手動建立
--
使用此選項、您可以從 AWS CloudForgation 擷取連結的 ARN 、並在此處報告。工作負載工廠會手動為您登錄連結。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在儲存設備中、選取 * 移至儲存設備詳細目錄 * 。
. 在 *FSX for ONTAP * 標籤中，選取檔案系統的三點功能表以建立連結，然後選取 * 建立連結 * 。
. 在關聯連結對話方塊中、選取 * 建立新連結 * 、然後選取 * 繼續 * 。
. 在「建立連結」頁面上、提供下列項目：
+
.. * 連結名稱 * ：輸入您要用於此連結的名稱。名稱在您的帳戶中必須是唯一的。
.. * AWS Secrets Manager* ：選用。允許工作負載工廠從 AWS Secrets Manager 擷取適用於 ONTAP 存取認證的 FSX 。
+
連結部署堆疊會自動將以下預設金鑰管理器 ARN 正規表示式新增至 Lambda 權限策略： `arn:aws:secretsmanager:<link_deployment_region>:<link_deployment_account_id>:secret:FSxSecret*` 。

+
您可以根據預設權限建立機密，或為連結原則指派自訂權限。

+
* 將 VPC 私有端點設定為 AWS Secrets Manager* 預設為停用。選取此選項會使用 VPC 私有端點儲存機密，而非儲存在本機。

.. *連結權限*：選擇以下連結權限選項之一：
+
*** *自動*：選擇此選項，以便 AWS CloudFormation 程式碼自動建立 Lambda 權限原則和執行角色。
*** *使用者提供*：選擇此選項可將指定的 Lambda 執行角色及其附加的策略指派給 Lambda 連結。 Lambda需要以下權限。 `secretsmanager:GetSecretValue`僅當您啟用 AWS Secrets Manager 時才需要權限。
+
[source, json]
----
"ec2:CreateNetworkInterface",
"ec2:DescribeNetworkInterfaces",
"ec2:DeleteNetworkInterface",
"ec2:AssignPrivateIpAddresses",
"ec2:UnassignPrivateIpAddresses"
"secretsmanager:GetSecretValue"
----
+
在文字方塊中輸入 Lambda 執行角色 ARN。



.. * 標記 * ：您也可以選擇新增任何標記來與此連結建立關聯、以便更輕鬆地將資源分類。例如、您可以新增一個標記、將此連結識別為由 FSX 用於 ONTAP 檔案系統。
.. *連結註冊*：選擇下拉箭頭以展開有關如何從 AWS CloudFormation 服務或使用 Terraform 註冊連結的說明。請依照指示進行。
+
請注意、當您啟動 CloudForgation 範本時、 Lambda 會獲得三個權限。工作負載工廠在使用連結時會使用這些權限。

+
[source, json]
----
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:UpdateFunctionCode"
----
+
成功建立堆疊後、將 Lambda ARN 貼到文字方塊中。

.. 工作負載工廠根據 FSx for ONTAP檔案系統自動擷取 AWS 帳戶、位置和安全群組。


. 選擇* Create *（建立*）。
+
您可以在事件頁面上監控連結建立狀態。這應該不會超過 5 分鐘。

. 返回工作負載原廠介面，您會看到連結與 ONTAP 檔案系統的 FSX 相關聯。


--
====
.結果
工作負載工廠將連結與 FSx for ONTAP檔案系統關聯。您可以執行進階ONTAP操作。



== 將現有連結與適用於 ONTAP 檔案系統的 FSX 建立關聯

建立連結之後，請將其與 ONTAP 檔案系統的一或多個 FSX 建立關聯。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在儲存設備中、選取 * 移至儲存設備詳細目錄 * 。
. 在 *FSX for ONTAP * 標籤中，選取檔案系統的三點功能表以建立連結，然後選取 * 建立連結 * 。
. 在「建立關聯」連結頁面中，選取 * 建立現有連結的關聯 * ，選取連結，然後選取 * 繼續 * 。
. 選取驗證模式。
+
** Workload Factory ：輸入密碼兩次。
** AWS Secrets Manager ：輸入機密 ARN 。
+
確保密鑰 ARN 包含下列密鑰有效對，儘管 _filesystemID_ 是可選的。

+
*** 檔案系統ID = FSx_filesystem_id（可選）
*** 使用者 = FSx_user
*** 密碼 = user_password
+

NOTE: 使用 AWS Secrets Manager 進行身份驗證需要一個用戶，可以是您提供的 _FSx_user_，也可以是在 FSx for ONTAP檔案系統上建立的其他用戶。預設用戶是 `fsxadmin`如果您不提供使用者。





. 選擇*應用*。


.結果
此連結與適用於 ONTAP 檔案系統的 FSX 相關聯。您可以執行進階 ONTAP 作業。



== 疑難排解 AWS Secrets Manager 連結驗證的問題

問題:: 連結缺少擷取機密的權限。
+
--
* 解析度 * ：在連結啟用後新增權限。登入 AWS 主控台，找到 Lambda 連結，然後編輯附加的權限原則。

--
問題:: 找不到機密。
+
--
* 解決方法 * ：提供正確的秘密 ARN 。

--
問題:: 機密格式不正確。
+
--
* 解析度 * ：前往 AWS Secrets Manager 並編輯格式。

密碼應包含下列金鑰有效配對：

* filesystemID = fsx_filesystem_id
* 使用者名稱 = FSx_user
* 密碼 = user_password


--
問題:: 機密不包含用於檔案系統驗證的有效 ONTAP 認證。
+
--
* 解析度 * ：提供認證，可在 AWS Secrets Manager 中驗證 ONTAP 檔案系統的 FSX 。

--

