---
sidebar: sidebar 
permalink: create-replication.html 
keywords: replication, replicate 
summary: 為適用於 ONTAP 檔案系統的 FSX 建立複寫關係、以避免在發生無法預見的災難時遺失資料。 
---
= 建立複寫關係
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
為適用於 ONTAP 檔案系統的 FSX 建立複寫關係、以避免在發生無法預見的災難時遺失資料。

.關於這項工作
複寫是新增的資料保護層、在資料所在的區域發生災難時、這是不可或缺的。如果您使用跨區域複寫、則可避免資料遺失。

此作業會為適用於 ONTAP 檔案系統的 FSX 中的一或所有來源磁碟區建立複寫關係。

目標檔案系統中的複寫磁碟區遵循下列命名格式 `{OriginalVolumeName}_copy`：。

.開始之前
開始之前、請確定您符合下列先決條件。

* 您的儲存設備庫存中必須有兩個可用的檔案系統、才能建立複寫關係。
* 您用於複寫關係的兩個檔案系統必須有相關的連結。如果檔案系統沒有現有的連結，請參閱 link:create-link.html["首先建立連結"]。link:manage-links.html["建立連結的關聯"]在檔案系統中、按一下 * 帳戶名稱 * 下的 * 關聯連結 * 。連結在兩個檔案系統中建立關聯後、請返回此作業。


請完成下列步驟來複寫單一磁碟區或複寫檔案系統中的所有磁碟區。

[role="tabbed-block"]
====
.複寫單一磁碟區
--
.步驟
. 登入 Workload Factory 主控台。
. 在儲存設備中、選取 * 移至儲存設備詳細目錄 * 。
. 在 *FSX for （用於 ONTAP ） * 選項卡中，選擇包含要複製的卷的文件系統的三點菜單，然後選擇 *Manag* （管理）。
. 從 Volumes （磁碟區）標籤中、選取要複寫的磁碟區的 thThree thots （三點）功能表。
. 選取 * 資料保護動作 * 、然後 * 複寫磁碟區資料 * 。
. 在「建立複寫」頁面的「複寫目標」下、提供下列項目：
+
.. * 適用於 ONTAP 檔案系統 * 的 FSX ：針對適用於 ONTAP 檔案系統的目標 FSX 、選取 ONTAP 檔案系統名稱的認證、區域和 FSX 。
.. * 儲存 VM 名稱 * ：從下拉式功能表中選取儲存 VM 。
.. *Volume name* ：目標 Volume 名稱會自動以下列格式產生 `{OriginalVolumeName}_copy`。您可以使用自動產生的 Volume 名稱或輸入其他 Volume 名稱。
.. * 分層原則 * ：選取儲存在目標 Volume 中的資料分層原則。
+
_Auto_ 是使用 ONTAP 使用者介面的 Workload Factory FSX 建立 Volume 時的預設分層原則。如需磁碟區分層原則的詳細資訊、請參閱 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Volume 儲存容量"^]AWS FSX for NetApp ONTAP 文件中的。

.. * 最大傳輸速率 * ：選取 * 受限 * 、然後以 MB/s 為單位輸入最大傳輸限制或者、選取 * 無限 * 。
+
如果沒有限制、網路和應用程式的效能可能會下降。或者、我們建議為 ONTAP 檔案系統的關鍵工作負載（例如主要用於災難恢復的工作負載）提供不限傳輸率的 FSX 。



. 在複寫設定下、提供下列項目：
+
.. * 複寫間隔 * ：選取快照從來源磁碟區傳輸到目標磁碟區的頻率。
.. * 長期保留 * ：可選擇啟用快照以進行長期保留。
+
如果您啟用長期保留、請選取現有原則或建立新原則、以定義要複寫的快照和要保留的數量。

+
... 若為 * 選擇現有原則 * 、請從下拉式功能表中選取現有原則。
... 對於 * 建立新原則 * 、請提供下列項目：
+
.... * 原則名稱 * ：輸入原則名稱。
.... * Snapshot Policies * ：在表格中、選取快照原則頻率和要保留的複本數量。您可以選取多個快照原則。






. 按一下「 * 建立 * 」。


--
.複寫檔案系統中的所有磁碟區
--
.步驟
. 登入 Workload Factory 主控台。
. 在儲存設備中、選取 * 移至儲存設備詳細目錄 * 。
. 在 FSX for （適用於 ONTAP 的 FSX ）標籤中、按一下含有磁碟區的檔案系統的三點功能表、然後選取 * 管理 * 。
. 從檔案系統總覽中、選取 * 建立複寫 * 。
. 在「建立複寫」頁面的「複寫目標」下、提供下列項目：
+
.. * 適用於 ONTAP 檔案系統 * 的 FSX ：針對適用於 ONTAP 檔案系統的目標 FSX 、選取 ONTAP 檔案系統名稱的認證、區域和 FSX 。
.. * 儲存 VM 名稱 * ：從下拉式功能表中選取儲存 VM 。
.. *Volume name* ：目標 Volume 名稱會自動以下列格式產生 `{OriginalVolumeName}_copy`。
.. * 分層原則 * ：選取儲存在目標 Volume 中的資料分層原則。
+
_Auto_ 是使用 ONTAP 使用者介面的 Workload Factory FSX 建立 Volume 時的預設分層原則。如需磁碟區分層原則的詳細資訊、請參閱 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Volume 儲存容量"^]AWS FSX for NetApp ONTAP 文件中的。

.. * 最大傳輸速率 * ：選取 * 受限 * 、然後以 MB/s 為單位輸入最大傳輸限制或者、選取 * 無限 * 。
+
如果沒有限制、網路和應用程式的效能可能會下降。或者、我們建議為 ONTAP 檔案系統的關鍵工作負載（例如主要用於災難恢復的工作負載）提供不限傳輸率的 FSX 。



. 在複寫設定下、提供下列項目：
+
.. * 複寫間隔 * ：選取快照從來源磁碟區傳輸到目標磁碟區的頻率。
.. * 長期保留 * ：可選擇啟用快照以進行長期保留。
+
如果您啟用長期保留、請選取現有原則或建立新原則、以定義要複寫的快照和要保留的數量。

+
... 若為 * 選擇現有原則 * 、請從下拉式功能表中選取現有原則。
... 對於 * 建立新原則 * 、請提供下列項目：
+
.... * 原則名稱 * ：輸入原則名稱。
.... * Snapshot Policies * ：在表格中、選取快照原則頻率和要保留的複本數量。您可以選取多個快照原則。






. 按一下「 * 建立 * 」。


--
====
.結果
複寫關係會出現在 * 複寫關係 * 索引標籤中。
