---
sidebar: sidebar 
permalink: enable-auto-capacity-management.html 
keywords: auto capacity, automatic capacity management, file system capacity 
summary: 啟用此功能可讓工作負載原廠自動將遞增儲存設備新增至適用於 ONTAP 檔案系統的 FSX ，以因應容量需求隨時間變化。 
---
= 為 ONTAP 檔案系統啟用 FSX 的自動容量管理
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
啟用自動容量管理後，BlueXP 工作負載工廠可根據容量需求隨時間變化自動為 FSx for ONTAP 檔案系統新增增量儲存。此外，啟用此功能無需手動監控容量，並降低了影響應用程式資料讀寫的風險。

.關於這項工作
每 30 分鐘掃描一次 ONTAP 檔案系統的 FSX ，以判斷是否需要新增遞增儲存設備，以及檢查可用的 Volume inode ，或是磁碟區中的檔案和資料夾數目上限，以便根據設定的自動容量管理臨界值來增加其數量。

只有一個帳戶可以管理此功能。

所有適用於 ONTAP 檔案系統的 FSX 的 SSD 儲存容量上限為 524,288 GiB 。若要要求增加配額、請參閱 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["配額"^] AWS FSX for NetApp ONTAP 文件中的。

.開始之前
開始之前請先考慮下列事項：

* 您必須擁有工作負載工廠中具有讀取/寫入權限的憑證才能完成此任務。
* 要確保卷 inode 隨着存儲容量的增加而增加link:manage-links.html["建立連結的關聯"]，您必須。如果您沒有現有的連結、 link:create-link.html["建立連結"]。若要在檔案系統中建立連結，請在 * 帳戶名稱 * 下選取 * 建立連結 * 。連結建立關聯後，請返回此作業。
* 您不應在資料遷移期間啟用此功能，因為 AWS 規定 SSD 容量增加之間至少需要六小時的冷卻期。此限制可能會延遲調整，因此請做好相應的規劃。


.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在 Storage （儲存設備）中、選取 * 前往 Storage inventory* （儲存設備庫存）。
. 在 * 適用於 ONTAP * 的 FSX 標籤中，選取檔案系統的三點功能表，以啟用的自動容量管理。
. 選擇*管理*。
. 在「資訊」下，選取 * 自動容量管理 * 旁的鉛筆圖示。當滑鼠移動到 * 自動容量管理 * 列上時、下拉式箭頭旁會出現鉛筆圖示。
. 在 * 自動容量管理 * 對話方塊中、提供下列項目：
+
.. * 認證 * ：從下拉式功能表中選取具有 _ 自動化 _ 權限的認證。
.. 選取啟用按鈕以 * 啟用自動容量管理 * 。
+
或者、停用此功能。如果您需要增加檔案系統容量、則必須先停用自動容量管理。

.. * 增加閾值 * ：輸入 ONTAP 檔案系統的 FSX 大小上限。
.. * 遞增增加 * ：輸入遞增容量的百分比。
.. 選用：啟用自動 inode 管理，以確保每個 Volume 的檔案容量會增加，方法是將 inode （檔案）數量增加到允許的上限。


. 選擇*應用*。


.結果
每 30 分鐘進行一次檔案系統掃描，以判斷檔案系統是否需要額外容量。
