---
sidebar: sidebar 
permalink: enable-auto-capacity-management.html 
keywords: auto capacity, automatic capacity management, inodes management, file system capacity 
summary: 啟用此功能後，Workload Factory 可以根據容量需求隨時間的變化，自動為 FSx for ONTAP檔案系統新增增量儲存或 inode。 
---
= 啟用檔案系統的自動容量和 inode 管理
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
啟用自動容量和 inode 管理後， NetApp Workload Factory可以根據容量需求隨時間的變化，自動在 FSx for ONTAP檔案系統中新增增量儲存或 inode。此外，啟用此功能後，就無需手動監控容量和 inode 了。



== 關於這項工作

每 30 分鐘對 FSx for ONTAP檔案系統進行一次掃描，以確定是否需要添加增量存儲，並檢查可用的捲 inode、卷中文件和資料夾的最大數量，以便根據配置的自動容量管理閾值增加其計數。

只有一個帳戶可以管理此功能。

所有適用於 ONTAP 檔案系統的 FSX 的 SSD 儲存容量上限為 524,288 GiB 。若要要求增加配額、請參閱 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["配額"^] AWS FSX for NetApp ONTAP 文件中的。



== 啟用自動容量管理

啟用自動容量管理，自動增加儲存空間，直到達到 FSx for ONTAP檔案系統的最大容量限制。

.開始之前
開始之前請先考慮下列事項：

* 你必須link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["使用_檢視、規劃和分析_權限策略授予憑證"^]在 Workload Factory 中完成此任務。
* 為了確保磁碟區 inode 隨著儲存容量的增加而增加，您必須關聯一個連結。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何關聯現有連結或建立並關聯新連結"]。連結建立關聯後，請返回此作業。
* 您不應在資料遷移期間啟用此功能，因為 AWS 規定 SSD 容量增加之間至少需要六小時的冷卻期。此限制可能會延遲調整，因此請做好相應的規劃。


.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在儲存圖塊中，選擇*轉到儲存*。
. 從儲存選單中，選擇 *FSx for ONTAP*。
. 從 *FSx for ONTAP* 中，選擇檔案系統的操作選單以啟用自動容量管理。
. 選擇*管理*。
. 在「資訊」下，選取 * 自動容量管理 * 旁的鉛筆圖示。當滑鼠移動到 * 自動容量管理 * 列上時、下拉式箭頭旁會出現鉛筆圖示。
. 在 * 自動容量管理 * 對話方塊中、提供下列項目：
+
.. * 認證 * ：從下拉式功能表中選取具有 _ 自動化 _ 權限的認證。
.. 選取啟用按鈕以 * 啟用自動容量管理 * 。
+
或者、停用此功能。如果您需要增加檔案系統容量、則必須先停用自動容量管理。

.. *警告閾值*：將警告閾值設定為低於觸發工作負載工廠通知服務的閾值增加值。預設值為 70%。
+
只有在您滿足以下條件時，警告閾值設定才可用：link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["啟用工作負載工廠通知服務"^] 。

.. *閾值增加*：輸入 FSx for ONTAP檔案系統的最大百分比增加值。預設值為 80%。
+
這是工作負載工廠觸發作業以增加容量的閾值。例如，如果檔案系統達到 80% 的容量，則 Workload Factory 將增加容量。

.. *增量增加*：輸入增量增加產能的百分比。預設值為 10%。
+
這是每次達到閾值時我們增加產能的百分比。例如，如果檔案系統已使用 80%，且增量設定為 10%，則 Workload Factory 會將容量增加 10%。



. 選擇*應用*。


.結果
每 30 分鐘進行一次檔案系統掃描，以判斷檔案系統是否需要額外容量。



== 啟用自動 inode 管理

啟用自動 inode 管理，確保每個磁碟區的檔案容量透過增加 inode（檔案）的數量來擴展，直到達到允許的限制。


NOTE: *Terraform 使用者*：Terraform 有限制，要求所有操作都必須在 Terraform 內部完成。  Terraform 不支援 inode 管理，但您可以在 Workload Factory 控制台中啟用自動 inode 管理。

.開始之前
開始之前請先考慮下列事項：

* 若要自動管理磁碟區 inode，必須關聯一個連結。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何關聯現有連結或建立並關聯新連結"]。連結關聯後，返回此操作。
* 可以透過設定_警告閾值_來設定自動 inode 管理，該閾值會觸發 Workload Factory 通知服務的通知。要使用此功能，您必須link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["啟用工作負載工廠通知服務"^]第一的。
* 你必須link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["使用_檢視、規劃和分析_權限策略授予憑證"^]在 Workload Factory 中完成此任務。


.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在儲存圖塊中，選擇*轉到儲存*。
. 從儲存選單中，選擇 *FSx for ONTAP*。
. 在 *FSx for ONTAP* 中，選擇檔案系統的操作選單以啟用自動 inode 管理。
. 選擇*管理*。
. 在「資訊」下，選擇「自動 inode 管理」旁的鉛筆圖示。當滑鼠停留在「自動 inode 管理」行上時，下拉箭頭旁邊會出現鉛筆圖示。
. 在「自動 inode 管理」對話方塊中，提供以下資訊：
+
.. * 認證 * ：從下拉式功能表中選取具有 _ 自動化 _ 權限的認證。
.. 選擇啟用按鈕以*啟用自動 inode 管理*。
+
或者，停用該功能。如果需要增加 inode 的數量，必須先停用自動 inode 管理。

.. *警告閾值*：將警告閾值設定為低於觸發工作負載工廠通知服務的閾值增加值。預設值為 70%。
+
只有在您滿足以下條件時，警告閾值設定才可用：link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["啟用工作負載工廠通知服務"^] 。

.. *閾值增加*：輸入每個磁碟區的 inode（檔案）數量的最大百分比增加量。預設值為 80%。
.. *增量增加*：輸入增量增加 inode（檔案）數量的百分比。預設值為 10%。


. 選擇*應用*。


.結果
每 30 分鐘進行一次檔案系統掃描，以確定每個磁碟區是否需要額外的 inode（檔案）。
