---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, fsx, ontap 
summary: 已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。 
---
= Amazon FSX for NetApp ONTAP 的已知限制
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。



== 區域支持

以下 AWS 區域不受支援：

* 中國地區
* GovCloud（美國）區域
* 秘密雲
* 絕密雲




== 新增 HA 配對限制

* 此作業可能需要約 30 分鐘的時間才能完成。
* 新增 HA 配對會限制下列作業：新增更多 HA 配對，配置 IOPS ，增加 SSD 容量，以及更新處理量容量。




== 處理量容量區域支援



=== 橫向擴充部署

所有地區均支援最高每秒 2 Gb 的橫向擴充組態。下列地區支援最高每秒 4 Gb 的最大處理量容量、可進行橫向擴充部署：美國東部（俄亥俄州）地區、美國東部（北維吉尼亞州）地區、美國西部（俄勒岡州）地區和歐洲（愛爾蘭）。



=== 橫向擴充部署

以下區域支援高達 6 GB/s 的最大吞吐容量，以進行橫向擴展部署：美國東部（弗吉尼亞北部和俄亥俄）、美國西部（加利福尼亞北部和俄勒岡）、歐洲（法蘭克福、愛爾蘭和斯德哥爾摩）以及亞太地區（新加坡和雪梨）。



== 容量管理

* iSCSI 傳輸協定目前不支援 Volume 自動擴充功能。
* 當自動容量管理功能正在執行時、不允許手動增加容量。
* 只有在啟用自動容量管理功能時、才能使用相同的權限來停用該功能。
* 當啟用自動容量管理時，需要一個連結來確保磁碟區 inode 隨著儲存容量一起增加。




== 儲存VM

每個 SKU 的儲存 VM 數量有限。工作負載工廠不支援建立超出限制的儲存 VM 。 ^1^

如需每個檔案系統的 SVM 最大數量、請參閱 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["管理 ONTAP 儲存虛擬機器的 FSX"^] AWS 文件中的。



== iSCSI 傳輸協定支援

* iSCSI 傳輸協定僅適用於 FlexVol 磁碟區。^1^
* 每個磁碟區只能設定單一 LUN 。




== 資料保護

* 無法刪除快照。
* 當您複寫檔案系統時、檔案系統中的所有磁碟區都會使用相同的複寫原則。
* 對於長期保留複寫關係，只有最後一個快照可供還原。
* 不可變快照不支援下列功能：
+
** 一致性群組
** FabricPool
** 資料量FlexCache
** SMtape
** SnapMirror 主動同步
** 使用 -schedule 參數的 SnapMirror 原則規則
** SnapMirror 同步
** SVM 資料移動性（用於將 SVM 從來源叢集移轉或重新定位至目的地叢集）






== 儲存節約計算機

儲存節約計算機無法計算下列組態的成本節約效益：

* 適用於 Windows 檔案伺服器的 FSX ： HDD 儲存類型
* 彈性區塊存放區（ EBS ）： ST1 、 SC1 和標準 Volume 類型
* 彈性檔案系統（ EFS ）：突增處理量模式




== 系統管理員

System Manager 不支援用於 ONTAP 連線的 FSX 連結。



== AWS Secrets Manager 支援

使用 Connector 時不支援 AWS Secrets Manager 。

附註：

. 適用於 Amazon FSX for NetApp ONTAP

