---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: Workload Factory 連結在 Workload Factory 帳戶和一個或多個 FSx for ONTAP檔案系統之間建立信任關係和連線。 
---
= 了解有關NetApp Workload Factory 連結的信息
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory 連結在 Workload Factory 帳戶和一個或多個 FSx for ONTAP檔案系統之間建立信任關係和連線。這可讓您直接從ONTAP REST API 呼叫監控和管理某些檔案系統功能，而這些功能無法透過Amazon FSx for ONTAP API 取得。

您不需要連結即可開始使用 Workload Factory，但在某些情況下，您需要建立連結來解鎖所有 Workload Factory 功能和工作負載能力。



== 為什麼連結是有益的

連結很有用，因為它們允許 Workload Factory 執行透過Amazon FSx for ONTAP API 本身無法執行的操作。連結支援高階ONTAP功能和自動化，從而增強 FSx for ONTAP檔案系統的管理。

以下是使用連結的一些好處：

* 此連結使NetApp控制台能夠將ONTAP指令直接傳送到您的 FSx for ONTAP檔案系統，從而帶來 AWS 原生提供的ONTAP進階功能。
* 連結利用 AWS Lambda 執行程式碼來回應事件。這種無伺服器方法消除了對 VPC 中運行實例的依賴。




== 連結的運作方式

連結運用 AWS Lambda 。Lambda 會回應事件執行程式碼、並自動管理該程式碼所需的運算資源。您建立的連結是 NetApp 帳戶的一部分、它們與 AWS 帳戶相關聯。

建立連結後，您可以將其與一個或多個 FSx for ONTAP檔案系統關聯。每個檔案系統只能與同一個 NetApp 帳戶中的一個連結建立關聯。如果您有多個 NetApp 帳戶、則單一檔案系統可以與不同 NetApp 帳戶下的其他連結建立關聯。

您可以在工作負載工廠中建立並關聯來自儲存工作負載的連結。

您可以使用儲存在 Workload Factory 憑證服務中的憑證或儲存在 AWS Secrets Manager 中的憑證來驗證連結。工作負載工廠不支援更改身份驗證模式。



== 成本

Lambda 執行的每筆交易都會產生費用。由於 Lambda 充當兩個系統之間的代理，因此當 Lambda 向檔案系統上的ONTAP REST API 發送請求時以及將回應傳送回 Workload Factory 時都會產生費用。

link:https://aws.amazon.com/lambda/pricing/["深入瞭解使用 AWS Lambda 的相關成本"^]



== 需要連結時

工作負載工廠需要一個連結來顯示一些資訊並執行一些任務。如果您嘗試執行需要連結的操作，但尚未將連結與 FSx for ONTAP檔案系統關聯，則 Workload Factory 會通知您該操作需要連結。

需要連結的功能包括：

* FSx for ONTAP檔案系統配置的良好架構狀態，可實現主動維護、可靠性和成本效益最佳化
* NetApp自主勒索軟體防護 (ARP/AI)
* 增強了 FSx for ONTAP檔案系統的整體容量可觀察性
* 捲和儲存虛擬機器資料複製、管理和監控
* SMB/CIFS 共用和 NFS 匯出策略設定和管理
* 在適用於 ONTAP 檔案系統的 FSX 上管理 iSCSI 磁碟區
* 建立和管理自訂保護 SLA 的快照策略
* 增強 Inode 管理以實現自動容量管理
* 容量自動成長以實現彈性擴展
* 克隆創建和管理，用於即時、就地資料克隆
* 直接從ONTAP顯示其他指標，例如ONTAP版本


瞭解如何link:create-link.html["將連結連接到 FSx for ONTAP檔案系統"]。
