---
sidebar: sidebar 
permalink: manage-snapshot-policy.html 
keywords: manage snapshot policy, change snapshot policy, snapshot policies, snapshot schedule, update 
summary: 在工作負載工廠中管理 FSx for ONTAP 磁碟區的快照策略。Snapshot 原則定義系統如何為磁碟區建立快照。 
---
= 管理快照原則
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
在工作負載工廠中管理 FSx for ONTAP 磁碟區的快照策略。Snapshot 原則定義系統如何為磁碟區建立快照。

.關於這項工作
在 ONTAP 檔案系統的 FSX 中指派，變更及刪除磁碟區的快照管理作業，都是在儲存 VM 層級進行管理。Snapshot 原則可與單一儲存 VM 或所有儲存 VM 共用。

某些管理任務要求您將連結與 FSx for ONTAP 檔案系統關聯。link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["了解工作負載工廠鏈接"]。

根據預設、每個磁碟區都會與檔案系統的快照原則相關聯 `default` 。我們建議大多數工作負載都使用此原則。



== 變更快照原則

您可以變更要保留的快照原則名稱，排程和複本數量，以及啟用或停用不可變快照。無法啟用或停用跨儲存 VM 的原則共用。此選項僅在建立快照原則時可用。

.開始之前
若要顯示現有的快照策略，您必須關聯一個連結。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何關聯現有連結或建立並關聯新連結"]。連結建立關聯後，請返回此作業。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在 * 儲存 * 中、選取 * 移至儲存設備詳細目錄 * 。
. 在 *FSX for （用於 ONTAP ） * 選項卡中，選擇文件系統的三點菜單，然後選擇 *Manag* （管理）。
. 在檔案系統總覽中，選取 * 儲存 VMS* 標籤。
. 從 * 儲存 VMS* 索引標籤中，針對包含要以排程快照保護之磁碟區的儲存 VM 選取三點功能表，然後選取 * 進階動作 * ，再選取 * 管理快照原則 * 。
. 在「 Snapshot 原則管理」頁面上，選取要變更快照原則的三點功能表，然後選取 * 編輯 * 。
. 在「編輯快照原則」對話方塊中，對快照原則進行必要的變更。
. 選擇*應用*。


.結果
快照原則已更新。



== 啟用不可變快照

鎖定快照，防止在保留期間刪除快照。

.開始之前
您必須關聯一個連結才能啟用不可變快照。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何關聯現有連結或建立並關聯新連結"]。連結建立關聯後，請返回此作業。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在 * 儲存 * 中、選取 * 移至儲存設備詳細目錄 * 。
. 在 *FSX for ONTAP * 標籤中，選取包含要鎖定快照之磁碟區的檔案系統三點功能表，然後選取 * 管理 * 。
. 在檔案系統總覽中、選取 * Volumes （磁碟區） * 標籤。
. 從 *Volumes （卷） * 選項卡中，選擇要保護的卷的三點菜單。
. 選擇 * 資料保護動作 * ， * 快照 * ，然後 * 建立不可變的快照 * 。
. 在「製作不可變的快照」對話方塊中，執行下列步驟：
+
.. * Snapshot name* ：選擇要鎖定的快照。
.. 將 * 保留期間 * 設定為小時數，天數，月數或年數。
.. 接受聲明。


. 選擇*應用*。


.結果
Volume 快照現在已鎖定。



== 將快照原則指派給磁碟區

您可以將快照原則指派給單一磁碟區，為該磁碟區建立排程快照。

.開始之前
您必須關聯一個連結才能指派快照策略。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何關聯現有連結或建立並關聯新連結"]。連結建立關聯後，請返回此作業。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在 * 儲存 * 中、選取 * 移至儲存設備詳細目錄 * 。
. 在 *FSX for ONTAP * 標籤中，選取包含要指派快照原則之磁碟區的檔案系統三點功能表，然後選取 * 管理 * 。
. 在檔案系統總覽中，選取 * 儲存 VMS* 標籤。
. 從 * 儲存 VMS* 索引標籤中，針對包含要以排程快照保護之磁碟區的儲存 VM 選取三點功能表，然後選取 * 進階動作 * ，再選取 * 管理快照原則 * 。
. 在「 Snapshot 原則管理」頁面上，選取快照原則的三點功能表，然後選取 * 將原則指派給 Volume * 。
. 在指派快照原則對話方塊中，選取要指派給磁碟區的快照原則，然後檢閱原則排程。
+
如果原則包含不可變的快照，而且您想要使用，請接受該陳述。

. 選取 * 指派 * 。


.結果
快照原則會指派給磁碟區。



== 從磁碟區移除快照原則

因為您不再需要磁碟區的快照，或是想要刪除指派給多個磁碟區的快照原則，所以請從磁碟區移除快照原則。若要<<刪除快照原則,刪除快照原則>>將其指派給多個 Volume ，您必須手動將其從所有 Volume 中移除。

.開始之前
您必須關聯一個連結才能刪除快照策略。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何關聯現有連結或建立並關聯新連結"]。連結建立關聯後，請返回此作業。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在 * 儲存 * 中、選取 * 移至儲存設備詳細目錄 * 。
. 在 *FSX for ONTAP * 標籤中，選取包含要指派快照原則之磁碟區的檔案系統三點功能表，然後選取 * 管理 * 。
. 在檔案系統總覽中，選取 * 儲存 VMS* 標籤。
. 從 * 儲存 VMS* 索引標籤中，針對包含要以排程快照保護之磁碟區的儲存 VM 選取三點功能表，然後選取 * 進階動作 * ，再選取 * 管理快照原則 * 。
. 在「 Snapshot 原則管理」頁面上，選取快照原則的三點功能表，然後選取 * 將原則指派給 Volume * 。
. 在 Assign snapshot policy （分配快照策略）對話框中，選擇 *None* （無）以刪除快照策略。
. 選取 * 指派 * 。


.結果
快照原則會從磁碟區中移除。



== 刪除快照原則

當您不再需要快照原則時，請將其刪除。

將快照原則指派給多個磁碟區時，您必須手動<<從磁碟區移除快照原則,將其移除>>從所有磁碟區中刪除快照原則。或者，您也可以<<將快照原則指派給磁碟區,指派不同的快照原則>>移至磁碟區。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在 * 儲存 * 中、選取 * 移至儲存設備詳細目錄 * 。
. 在 *FSX for ONTAP （用於卷的 FSX ） * 選項卡中，選擇包含卷的文件系統的三點菜單，然後選擇 *Manag* （管理）。
. 在檔案系統總覽中，選取 * 儲存 VMS* 標籤。
. 從 * 儲存 VMS* 索引標籤中，選擇儲存 VM 的三點功能表，並選擇要刪除的快照原則，然後選擇 * 進階動作 * ，再選擇 * 管理快照原則 * 。
. 在「 Snapshot 原則管理」頁面上，選取要刪除之快照原則的三點功能表，然後選取 * 刪除 * 。
. 在刪除對話方塊中，選取 * 刪除 * 以刪除原則。


.結果
快照原則即會刪除。
