---
sidebar: sidebar 
permalink: pause-resume-replication.html 
keywords: pause replication, quiesce replication, resume replication 
summary: 暫停並恢復複寫關係，使目標 Volume 成為來源 Volume 。 
---
= 在NetApp Workload Factory 中暫停和恢復複製關係
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
暫停複寫關係，以停止從來源磁碟區到目標磁碟區的排程複寫更新。目標 Volume 會從唯讀轉換為讀寫。這兩個磁碟區會繼續共用最新的複寫快照，作為日後重新同步的新基準。

.關於這項工作
暫停時，來源磁碟區和目標磁碟區之間的複寫關係會繼續存在。資料傳輸會暫停，而且磁碟區會變得不再是問題。若要重新啟用變更從來源磁碟區傳輸至目的地磁碟區的功能，請繼續複寫。

當您恢復複製時，目標磁碟區的所有變更都會被撤銷，並且NetApp Workload Factory 將重新啟用複製。目標磁碟區從讀取/寫入轉換為唯讀，並再次按照計劃的複製間隔從來源磁碟區接收更新。當您恢復複製關係時，目標磁碟區將恢復到最新的初始複製快照，此時，磁碟區複製程序重新開始。

.開始之前
如果您在傳輸進行時暫停，傳輸將不會受到影響，而且在傳輸完成之前，關係會變成「靜止」。如果目前傳輸中斷，現在是未來傳輸，不會重新啟動。



== 暫停複寫關係

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在儲存圖塊中，選擇*轉到儲存*。
. 從儲存選單中，選擇 *FSx for ONTAP*。
. 從 *FSx for ONTAP* 中，選擇要更新的檔案系統的操作選單，然後選擇 *管理*。
. 從檔案系統總覽中、選取 * 複寫關係 * 索引標籤。
. 在複製關係標籤中，選擇要暫停的複製關係的操作選單。
. 選取 * 暫停（靜止） * 。
. 在 * 靜止關係 * 對話方塊中，選取 * 靜止 * 。


.結果
關係會暫停，其狀態顯示為「暫停」。



== 恢復暫停的複寫關係

當您恢復複寫關係時，在複寫停止時對目的地磁碟區所做的任何變更都會被刪除。


NOTE: 在上次資料複寫與停用來源磁碟區之間、寫入原始來源磁碟區的任何資料都不會保留。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在儲存圖塊中，選擇*轉到儲存*。
. 從儲存選單中，選擇 *FSx for ONTAP*。
. 從 *FSx for ONTAP* 中，選擇要更新的檔案系統的操作選單，然後選擇 *管理*。
. 從檔案系統總覽中、選取 * 複寫關係 * 索引標籤。
. 在複製關係標籤中，選擇要復原的複製關係的操作選單。
. 選取 * 繼續 * 。
. 在「恢復關係」對話方塊中，選取 * 繼續 * 。


.結果
關係隨即恢復，其狀態顯示為「已複寫」。
