---
sidebar: sidebar 
permalink: ransomware-protection.html 
keywords: ransomware, arp, autonomous protection, protect, security, detect, detection, restore, recover, threat, attack, suspect, anti-ransomware, entropy, abnormal volume activity, anti-ransomware, extension conformity, ransomware protection strategy 
summary: 自主勒索軟體保護會在 NAS 環境中使用工作負載分析、偵測並警告可能是勒索軟體攻擊的異常活動。 
---
= 運用自主勒索軟體保護來保護資料
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
使用自動勒索軟體保護（ ARP ）來保護您的資料，這項功能會在 NAS （ NFS/SMB ）環境中使用工作負載分析來偵測並警告可能是勒索軟體攻擊的異常活動。當懷疑有攻擊時， ARP 也會建立新的不可變快照，您可以從中還原資料。

.關於這項工作
使用 ARP 來防範阻斷服務攻擊，攻擊者會在支付贖金之前，先將資料保留在攻擊者的位置。ARP 會根據下列項目提供即時勒索軟體偵測：

* 將傳入資料識別為加密或純文字。
* 可偵測下列項目的分析：
+
** ** Entropy** ：評估檔案中資料的隨機性
** ** 檔案副檔名類型 ** ：不符合一般副檔名類型的副檔名
** ** 檔案 IOPS ** ：資料加密的異常 Volume 活動激增




在僅加密少數檔案、自動採取行動保護資料、並在發生可疑攻擊時發出警示、因此、ARP可以偵測大多數勒索軟體攻擊的擴散。

ARP 功能會根據 Amazon FSX for NetApp ONTAP 執行的 ONTAP 版本自動更新，因此您不需要手動更新。

學習和作用中模式:: ARP 會先以 _ 學習模式 _ 運作，然後自動切換至 _ 作用中模式 _ 。
+
--
* * 學習模式 * ：當您啟用 ARP 時，它會以 _ 學習模式 _ 執行。在學習模式中，適用於 ONTAP 檔案系統的 FSX 會根據分析領域開發警示設定檔： Entropy ，檔案副檔名類型和檔案 IOPS 。檔案系統以學習模式執行 ARP ，並有足夠時間評估工作負載特性之後，工作負載工廠會自動切換至 ARP 模式，並開始保護您的資料。
* * 作用中模式 * ：在 ARP 切換至 _active modes_ 之後， ONTAP 的 FSX 會建立 ARP/AI 快照，以在偵測到威脅時保護資料。
+
在作用中模式中、如果檔案副檔名標示為異常、您應該評估警示。您可以對警示採取行動以保護資料、也可以將警示標記為誤報。將警示標記為誤報會更新警示設定檔。例如、如果警示是由新的副檔名觸發、而您將警示標記為誤判、則下次觀察到該副檔名時、您將不會收到警示。



--
不支援的組態:: 下列組態不支援使用 ARP 。
+
--
* SAN / 區塊磁碟區
* iSCSI磁碟區
* NVMe 磁碟區


--




== 為檔案系統啟用自主勒索軟體保護

啟用檔案系統的 ARP 可自動為所有現有的 NAS 和新建立的 NAS 磁碟區提供保護。

啟用 ARP 之後，如果發生攻擊且您發現攻擊是真實的， BlueXP  工作負載工廠會自動設定快照原則，每四小時最多需要六個快照。每個快照都會鎖定 2-5 天。

.開始之前
要爲文件系統啓用 ARP ，您必須link:manage-links.html["建立連結的關聯"]。如果您沒有現有的連結、 link:create-link.html["建立連結"]。若要在檔案系統中建立連結，請在 * 帳戶名稱 * 下選取 * 建立連結 * 。連結建立關聯後，請返回此作業。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在 Storage （儲存設備）中、選取 * 前往 Storage inventory* （儲存設備庫存）。
. 在 *FSX for ONTAP * 標籤中，選取檔案系統的三點功能表以啟用 ARP ，然後選取 * 管理 * 。
. 在「資訊」下，選取 * 自主勒索軟體保護 * 旁的鉛筆圖示。當滑鼠移動到 *Autosomware Protection* 資料列上時，下拉式箭頭旁會出現鉛筆圖示。
. 在「自主勒索軟體保護」對話方塊中，啟用或停用此功能。
. 接受聲明以繼續。
. 選取 * 套用 * 以儲存變更。




== 驗證勒索軟體攻擊

判斷攻擊是假警報還是真正的勒索軟體事件。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在 Storage （儲存設備）中、選取 * 前往 Storage inventory* （儲存設備庫存）。
. 從檔案系統總覽中、選取 * Volumes （磁碟區） * 標籤。
. 從「自主勒索軟體保護」磚中選取 * 分析攻擊 * 。
. 下載攻擊事件報告，檢閱是否有任何檔案或資料夾遭到入侵，然後決定是否發生攻擊。
. 如果未發生攻擊，請在表格中選取 * 錯誤警報 * 作為磁碟區，然後選取 * 關閉 *
. 如果發生攻擊，請針對表格中的磁碟區選取 * 實際攻擊 * 。「還原遭入侵的 Volume 資料」對話方塊隨即開啟。您可以立即進入<<在勒索軟體攻擊之後恢復資料,恢復您的資料>>或選擇 * 關閉 * ，稍後再回來完成恢復程序。




== 在勒索軟體攻擊之後恢復資料

當懷疑有攻擊時，系統會在該時間點擷取磁碟區快照，並鎖定該複本。如果稍後確認攻擊，則可使用 ARP 快照還原受影響的檔案或整個磁碟區。

在保留期間結束之前，無法刪除鎖定的快照。不過、如果您稍後決定將攻擊標示為誤判、則鎖定的複本將會刪除。

瞭解受影響的檔案和攻擊時間後，您可以選擇性地從各種快照中復原受影響的檔案，而不只是將整個磁碟區還原為其中一個快照。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在 Storage （儲存設備）中、選取 * 前往 Storage inventory* （儲存設備庫存）。
. 從檔案系統總覽中、選取 * Volumes （磁碟區） * 標籤。
. 從「自主勒索軟體保護」磚中選取 * 分析攻擊 * 。
. 如果發生攻擊，請針對表格中的磁碟區選取 * 實際攻擊 * 。
. 在還原遭入侵的磁碟區資料對話方塊中，依照指示在檔案層級或磁碟區層級還原。在大多數情況下，您會還原檔案，而非整個磁碟區。
. 完成還原後，選取 * 關閉 * 。


.結果
已還原遭入侵的資料。
