---
sidebar: sidebar 
permalink: rebalance-volume.html 
keywords: rebalance capacity, volume capacity, redistribute capacity 
summary: 檢查並重新平衡磁碟區的容量，以避免隨著時間而產生的不平衡現象。 
---
= 檢查並重新平衡磁碟區的容量
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
檢查 FlexGroup Volume 容量的平衡，並重新平衡磁碟區容量，以便將檔案平均分散到所有組成區，讓所有節點都能參與單一 Flex Group Volume 的工作負載。

.關於這項工作
FlexGroup Volume 容量分散在橫向擴充的 FSX 中，適用於具有兩個或更多高可用度（ HA ）配對的 ONTAP 檔案系統。每個組成都是指定最大單一檔案大小的容器。適用於 ONTAP 的 FSX 會以均勻的方式跨所有成員分散檔案，讓所有節點都能參與單一 FlexGroup Volume 的工作負載。

當組成要素未平均分散於所有節點時， FlexGroup Volume 效能會降低。

檢查 FlexGroup Volume 容量的平衡，包括評估組成的目前配置。當您重新平衡磁碟區的容量時， BlueXP  工作負載工廠會設計一個新的組成配置，其中包含偶數個組成成分，以便在所有 HA 配對之間平均分散資料。服務會執行重新平衡計畫，進而改善讀寫作業。

重新平衡磁碟區會在新增檔案和檔案成長、隨著時間的推移而產生不平衡時、重新分配容量。手動開始重新平衡作業後、我們會選取檔案、並自動且不中斷地移動。Volume 傳輸作業會消耗檔案系統資源。


NOTE: 只有 FlexGroup 磁碟區才支援重新平衡，但 iSCSI 或 NVMe FlexGroup 磁碟區則不支援重新平衡。



== 檢查 FlexGroup Volume 的平衡

檢查作用中 FlexGroup Volume 的平衡。

.開始之前
* FlexGroup Volume Balance 僅適用於使用橫向擴充部署且至少有兩個 HA 配對的 ONTAP 檔案系統。
* Volume 樣式必須是 FlexGroup Volume 。
* 要檢查 FlexGroup 磁碟區的餘額，您必須關聯一個連結。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何關聯現有連結或建立並關聯新連結"]。連結建立關聯後，請返回此作業。


.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在 * 儲存 * 中、選取 * 移至儲存設備詳細目錄 * 。
. 在 *FSX for （用於 ONTAP ） * 選項卡中，選擇包含要重新平衡的卷的文件系統的三點菜單，然後選擇 *Manag* （管理）。
. 從檔案系統總覽中、選取 * Volumes （磁碟區） * 標籤。
. 從 Volumes （卷）選項卡中，選擇表頂部的 *Check Balance* （檢查 FlexGroup 平衡）。
. 在 Balance （ FlexGroup 平衡）視窗中，檢閱適用於 ONTAP 檔案系統的 FSX 中所有 FlexGroup Volume 的平衡狀態。
+
當 FlexGroup Volume 不平衡時，請考慮<<重新平衡 FlexGroup Volume,重新平衡>>。





== 重新平衡 FlexGroup Volume

重新平衡一個或多個非平衡的磁碟區。資料會在成員磁碟區之間重新分配，以重新平衡 FlexGroup 磁碟區。根據您偏好的資料發佈配置，重新平衡作業可能會新增 FlexGroup 成員磁碟區，並增加已佈建磁碟區的大小。


NOTE: 工作負載原廠管理員可在作業期間停止重新平衡。

.開始之前
* <<檢查 FlexGroup Volume 的平衡,檢查 FlexGroup Volume 的平衡>>重新平衡磁碟區之前。
* 要重新平衡卷，您必須關聯一個連結。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何關聯現有連結或建立並關聯新連結"]。連結建立關聯後，請返回此作業。
* 請注意，您重新平衡的磁碟區上現有的快照會變成部分快照，無法用來還原磁碟區資料，但重新平衡之後所拍攝的新快照可以用來還原磁碟區資料。


.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在 * 儲存 * 中、選取 * 移至儲存設備詳細目錄 * 。
. 在 *FSX for （用於 ONTAP ） * 選項卡中，選擇包含要重新平衡的卷的文件系統的三點菜單，然後選擇 *Manag* （管理）。
. 從檔案系統總覽中、選取 * Volumes （磁碟區） * 標籤。
. 從 Volumes （卷）選項卡中，選擇表頂部的 *Check Balance* （檢查 FlexGroup 平衡）。
. 在 Balance （ FlexGroup 平衡）視窗中，選取 * Rebalanc* （重新平衡）以重新平衡一個或多個非平衡的磁碟區。
. 在重新平衡精靈中，選取您偏好的資料發佈配置。
+
** * 效能最佳化 * （建議使用）：增加 FlexGroup 成員磁碟區的數量和磁碟區的資源配置大小。遵循 NetApp 最佳實務做法。
** * 限制 * ：支援複寫關係中的磁碟區。FlexGroup 成員磁碟區的數量和已佈建磁碟區的大小維持不變。如果所有選取的磁碟區都參與複寫關係，則預設會選取此選項。
** * 手冊 * ：選取每個 HA 配對所需的 FlexGroup 成員磁碟區數量。視您的選擇而定， FlexGroup 成員磁碟區的數量和已配置的磁碟區大小可能會增加。


. * 節流 * ：選用。預設為停用。啟用節流以限制磁碟區在檔案系統上移動的頻寬，並減緩傳出的磁碟區複寫流量。
+
以 MB/s 為單位輸入節流值

. 選取版面配置比較檢視，然後選取 * 下一步 * 。
+
** Volume 配置比較
** ONTAP 配置比較的 FSX


. 您也可以在重新平衡之前下載磁碟區移動清單。
. 選擇 * 重新平衡 * 。


.結果
視 FlexGroup 新增的 FlexGroup 成員磁碟區數量而定，一次只會執行一個 FlexGroup 磁碟區成員移動作業。當作業完成時，檔案系統將會被節流回原始值。
