---
sidebar: sidebar 
permalink: rebalance-volume.html 
keywords: rebalance capacity, volume capacity, redistribute capacity 
summary: 檢查並重新平衡容量以避免隨著時間的推移而出現不平衡。 
---
= 檢查並重新平衡磁碟區容量
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
檢查 FlexVol 或 FlexGroup 卷容量的平衡，並重新平衡磁碟區容量，以將檔案均勻分佈在節點中的所有 FlexVol 磁碟區或所有組成部分之間，以便所有節點都參與單一 FlexGroup 磁碟區的工作負載。



== 關於這項工作

FlexVol 捲和 FlexGroup 磁碟區支援重新平衡磁碟區容量。重新平衡磁碟區會在新增檔案和檔案成長、隨著時間的推移而產生不平衡時、重新分配容量。手動開始重新平衡作業後、我們會選取檔案、並自動且不中斷地移動。Volume 傳輸作業會消耗檔案系統資源。

每種磁碟區類型和重新平衡操作均有不同，如下所示。

.資料量FlexVol
FlexVol 卷是一種邏輯容器，能夠靈活地管理數據，支援擴展、收縮、移動和高效複製。它們適用於 NAS 和 SAN 環境。

在 FSx for ONTAP 檔案系統中，一個 FlexVol 磁碟區可以與一個節點內的其他 FlexVol 磁碟區進行平衡。如果檔案系統只有一個 FlexVol 卷，則無法進行重新平衡。當檔案系統每個節點有多個 FlexVol 磁碟區並且選擇了單一 FlexVol 磁碟區時，該 FlexVol 磁碟區會在所有 FlexVol 磁碟區的上下文中進行平衡，但只允許移動選取的磁碟區。

.資料量FlexGroup
另一方面，FlexGroup 磁碟區是可擴充的 NAS 容器，旨在實現高效能和自動負載分配。它們由多個成員卷（組成部分）組成，這些成員卷透明地共享流量。 FlexGroup卷提供海量容量，超越 FlexVol 的限制，最高可達 60PB 容量和 4000 億個檔案。它們透過提供單一命名空間容器來簡化管理。

容量分佈在具有兩個或更多高可用性 (HA) 對的橫向擴展 FSx for ONTAP 檔案系統的多個組成部分中。每個組成都是指定最大單一檔案大小的容器。適用於 ONTAP 的 FSX 會以均勻的方式跨所有成員分散檔案，讓所有節點都能參與單一 FlexGroup Volume 的工作負載。

當組成要素未平均分散於所有節點時， FlexGroup Volume 效能會降低。

檢查FlexGroup磁碟區容量的平衡包括評估組成部分的當前佈局。當您重新平衡磁碟區的容量時， NetApp Workload Factory 會設計一個具有偶數個組成部分的新組成部分佈局，以將資料均勻分佈在所有 HA 對中。此服務執行重新平衡計劃，從而改善讀寫操作。


NOTE: iSCSI 和 NVMe 等 SAN 磁碟區不支援重新平衡。



== 檢查您的交易量餘額

檢查 FSx for ONTAP 檔案系統中 FlexVol 或 FlexGroup 磁碟區的平衡。

.開始之前
* FlexGroup Volume Balance 僅適用於使用橫向擴充部署且至少有兩個 HA 配對的 ONTAP 檔案系統。
* 要檢查卷的餘額，您必須link:manage-links.html["建立連結的關聯"] 。如果您沒有現有的連結、 link:create-link.html["建立連結"]。若要在檔案系統中建立連結，請在 * 帳戶名稱 * 下選取 * 建立連結 * 。連結建立關聯後，請返回此作業。


.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在*儲存*中，選擇*前往儲存*。
. 從儲存選單中，選擇 *FSx for ONTAP*。
. 從 *FSx for ONTAP* 中，選擇包含要重新平衡的磁碟區的檔案系統的操作選單，然後選擇 *管理*。
. 從檔案系統總覽中、選取 * Volumes （磁碟區） * 標籤。
. 從「卷」標籤中，選擇表格頂部的「檢查卷餘額」。
. 在「交易量平衡」視窗中，查看以下平衡狀態：
+
** 資料量FlexGroup
** 資料量FlexVol
+
當音量不平衡時，請考慮<<重新平衡磁碟區容量,重新平衡>> 。







== 重新平衡磁碟區容量

重新平衡一個或多個非平衡的磁碟區。


NOTE: Workload Factory 管理員可以<<停止磁碟區重新平衡操作,停止重新平衡>>在操作過程中。

.開始之前
* <<檢查您的交易量餘額,檢查卷的餘額>>重新平衡磁碟區之前。
* 若要重新平衡磁碟區、您必須 link:manage-links.html["建立連結的關聯"]。如果您沒有現有的連結、 link:create-link.html["建立連結"]。若要在檔案系統中建立連結，請在 * 帳戶名稱 * 下選取 * 建立連結 * 。連結建立關聯後，請返回此作業。
* 請注意，您重新平衡的磁碟區上現有的快照會變成部分快照，無法用來還原磁碟區資料，但重新平衡之後所拍攝的新快照可以用來還原磁碟區資料。
* 最好將 FlexVol 磁碟區全部重新平衡，以便均勻平衡所有捲資源。取消選定的磁碟區不會主動參與平衡過程。


[role="tabbed-block"]
====
.流通量FlexVol
--
在 FSx for ONTAP 檔案系統中，一個 FlexVol 磁碟區可以與同一節點內的其他 FlexVol 磁碟區進行平衡。當檔案系統每個節點有多個 FlexVol 磁碟區且選擇了單一 FlexVol 磁碟區時，此 FlexVol 磁碟區會在所有 FlexVol 磁碟區的上下文中進行平衡，但只允許移動選取的磁碟區。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在*儲存*中，選擇*前往儲存*。
. 從儲存選單中，選擇 *FSx for ONTAP*。
. 從 *FSx for ONTAP* 中，選擇包含要重新平衡的磁碟區的檔案系統的操作選單，然後選擇 *管理*。
. 從檔案系統總覽中、選取 * Volumes （磁碟區） * 標籤。
. 從「卷」標籤中，選擇表格頂部的「檢查卷餘額」。
. 在磁碟區平衡視窗中，可以選擇 FlexVol 平衡摘要中的「*資料分佈*」來查看每個聚合的已使用容量。
. 選擇“*重新平衡*”以重新平衡一個或多個不平衡的捲。
. 在重新平衡精靈中，請依照下列步驟操作。
+
.. *最大傳輸速率*：可選。預設為停用。啟用節流以限制磁碟區在檔案系統上移動的頻寬，並減緩傳出的磁碟區複寫流量。
+
以 MB/s 為單位輸入節流值

+
選擇*下一步*。

.. 查看所有 FlexVol 卷的當前和建議佈局，然後選擇*下一步*。
.. 在開始重新平衡操作之前，請仔細檢查將會發生什麼以及注意事項。


. 選擇 * 重新平衡 * 。


.結果
FlexVol 卷已重新平衡。當作業完成時，檔案系統將會被節流回原始值。

--
.流通量FlexGroup
--
資料會在成員磁碟區之間重新分配，以重新平衡 FlexGroup 磁碟區。根據您選擇的佈局，重新平衡操作可能會新增 FlexGroup 成員磁碟區並增加已配置磁碟區的大小。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在*儲存*中，選擇*前往儲存*
. 從儲存選單中，選擇 *FSx for ONTAP*。
. 從 *FSx for ONTAP* 中，選擇包含要重新平衡的磁碟區的檔案系統的操作選單，然後選擇 *管理*。
. 從檔案系統總覽中、選取 * Volumes （磁碟區） * 標籤。
. 從 Volumes （卷）選項卡中，選擇表頂部的 *Check Balance* （檢查 FlexGroup 平衡）。
. 在 Balance （ FlexGroup 平衡）視窗中，選取 * Rebalanc* （重新平衡）以重新平衡一個或多個非平衡的磁碟區。
. 在重新平衡精靈中，選取您偏好的資料發佈配置。
+
** * 效能最佳化 * （建議使用）：增加 FlexGroup 成員磁碟區的數量和磁碟區的資源配置大小。遵循 NetApp 最佳實務做法。
** * 限制 * ：支援複寫關係中的磁碟區。FlexGroup 成員磁碟區的數量和已佈建磁碟區的大小維持不變。如果所有選取的磁碟區都參與複寫關係，則預設會選取此選項。
** * 手冊 * ：選取每個 HA 配對所需的 FlexGroup 成員磁碟區數量。視您的選擇而定， FlexGroup 成員磁碟區的數量和已配置的磁碟區大小可能會增加。


. * 節流 * ：選用。預設為停用。啟用節流以限制磁碟區在檔案系統上移動的頻寬，並減緩傳出的磁碟區複寫流量。
+
以 MB/s 為單位輸入節流值

. 選取版面配置比較檢視，然後選取 * 下一步 * 。
+
** Volume 配置比較
** ONTAP 配置比較的 FSX


. 您也可以在重新平衡之前下載磁碟區移動清單。
. 選擇 * 重新平衡 * 。


.結果
在重新平衡期間，FlexGroup 成員磁碟區一次移動一個。當作業完成時，檔案系統將會被節流回原始值。

--
====


== 停止磁碟區重新平衡操作

隨時停止重新平衡操作；這不會造成中斷。停止操作會中止正在進行的磁碟區移動。

您可以稍後開始另一個重新平衡操作。

.步驟
. 開始重新平衡操作後，從卷平衡頁面選擇*停止重新平衡*。
. 在停止重新平衡對話方塊中，選擇*停止*。


.結果
磁碟區重新平衡操作停止並且活動磁碟區移動中止。
