---
sidebar: sidebar 
permalink: replicate-svm-to-file-system.html 
keywords:  
summary: 將儲存 VM 複製到另一個適用於 ONTAP 檔案系統的 FSX 、可在資料遺失時提供保護層的資料存取。 
---
= 將儲存 VM 複寫到另一個適用於 ONTAP 檔案系統的 FSX
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
在NetApp Workload Factory 中將儲存虛擬機器複製到另一個 FSx for ONTAP檔案系統可在資料遺失時提供資料存取的保護層。此操作將一個儲存虛擬機器中的所有磁碟區複製到另一個 FSx for ONTAP檔案系統。

.開始之前
若要將儲存虛擬機器複製到另一個 FSx for ONTAP 檔案系統，您必須關聯一個連結。link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["了解如何關聯現有連結或建立並關聯新連結"]。連結建立關聯後，請返回此作業。

.步驟
. 使用其中一項登link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^]入。
. 在儲存圖塊中，選擇*轉到儲存*。
. 從儲存選單中，選擇 *FSx for ONTAP*。
. 從 *FSx for ONTAP* 中，選擇要複製儲存虛擬機器的檔案系統的操作選單，然後選擇 *管理*。
. 從檔案系統總覽中、選取 * 儲存 VMS* 標籤。
. 從「儲存虛擬機器」標籤中，選擇要為其複製 SVM 的儲存虛擬機器的操作選單。
. 選取 * 複寫儲存 VM* 。
. 在「建立複寫」頁面的「複寫目標」下、提供下列項目：
+
.. * 適用於 ONTAP 檔案系統 * 的 FSX ：針對適用於 ONTAP 檔案系統的目標 FSX 、選取 ONTAP 檔案系統名稱的認證、區域和 FSX 。
.. * 儲存 VM 名稱 * ：從下拉式功能表中選取儲存 VM 。
.. *Volume name* ：目標 Volume 名稱會自動以下列格式產生 `{OriginalVolumeName}_copy`。
.. * 分層原則 * ：選取儲存在目標 Volume 中的資料分層原則。
+
使用 Workload Factory FSx for ONTAP使用者介面建立磁碟區時，_Auto_ 是預設分層策略。有關卷分層策略的更多信息，請參閱link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Volume 儲存容量"^]在 AWS FSx for NetApp ONTAP文件中。

.. * 最大傳輸速率 * ：選取 * 受限 * 、然後以 MB/s 為單位輸入最大傳輸限制或者、選取 * 無限 * 。
+
如果沒有限制，網路和應用程式的效能可能會下降。或者、我們建議為 ONTAP 檔案系統的關鍵工作負載（例如主要用於災難恢復的工作負載）提供不限傳輸率的 FSX 。



. 在複寫設定下、提供下列項目：
+
.. * 複寫間隔 * ：選取快照從來源磁碟區傳輸到目標磁碟區的頻率。
.. * 長期保留 * ：可選擇啟用快照以進行長期保留。
+
如果您啟用長期保留、請選取現有原則或建立新原則、以定義要複寫的快照和要保留的數量。

+
... 若為 * 選擇現有原則 * 、請從下拉式功能表中選取現有原則。
... 對於 * 建立新原則 * 、請提供下列項目：
+
.... * 原則名稱 * ：輸入原則名稱。
.... * Snapshot Policies * ：在表格中、選取快照原則頻率和要保留的複本數量。您可以選取多個快照原則。






. 選擇* Create *（建立*）。


.結果
儲存 VM 中的所有磁碟區都會複寫到目標檔案系統。
