= BlueXP 工作負載工廠通知服務支持
:allow-uri-read: 




=== BlueXP 工作負載工廠通知服務支持

BlueXP 工作負載工廠通知服務支援工作負載工廠向 BlueXP 警報服務或 Amazon SNS 主題發送通知。發送到 BlueXP 警報的通知會顯示在 BlueXP 警報面板中。當工作負載工廠向 Amazon SNS 主題發布通知時，該主題的訂閱者（例如人員或其他應用程式）會在為該主題配置的終端節點上收到通知（例如電子郵件或簡訊）。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["配置 BlueXP 工作負載工廠通知"^]



=== 儲存儀表板增強功能

Workload Factory 控制台中的儲存儀表板包含用於節省機會的新卡片。儀表板頂部的卡片顯示在 Amazon Elastic Block Store (EBS)、 Amazon FSx for Windows File Server 和 Amazon Elastic File Systems (EFS) 上執行的儲存環境的節省機會數。在儀表板的底部，三張新卡片顯示了亞馬遜儲存服務的節省機會 - EBS、FSx for Windows File Server 和 EFS。您可以從所有卡片中更詳細地探索省錢機會。

透過 FSx for ONTAP 保護覆蓋率卡和複製關係健康卡，您可以調查 FSx for ONTAP 檔案系統中是否存在任何部分受保護的捲，以及調查複製關係的問題。在這兩種情況下，您都可以採取措施來解決問題。



=== 音量選項卡增強功能

Workload Factory 控制台中的「磁碟區」標籤已增強，可提供 FSx for ONTAP檔案系統的更全面的視圖。增強功能包括 SSD 容量、容量池和帶有 AI 的NetApp自主勒索軟體防護 (ARP/AI) 的新卡片。這些卡片總結了檔案系統中所有磁碟區的容量利用率和 ARP/AI 保護。



=== 支援第二代 Amazon FSX for NetApp ONTAP 檔案系統

工作負載工廠現在支援第二代Amazon FSx for NetApp ONTAP檔案系統。您可以在 Workload Factory 控制台中建立、管理和監控第二代檔案系統。所有新的商業區域均受支援。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["在 Workload Factory 中建立第二代檔案系統"]



=== FlexVol 磁碟區支援重新平衡磁碟區容量

FlexVol磁碟區可在 Workload Factory 控制台中發現。您可以檢查FlexVol磁碟區的平衡情況，並在因新檔案的新增和檔案成長而導致不平衡情況隨時間推移而出現時，重新平衡FlexVol磁碟區以重新分配容量。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["重新平衡 FlexVol 卷的容量"]



=== 術語更新

在 Workload Factory 控制台中，「自主勒索軟體防護」(ARP) 一詞已更新為「具有 AI 的NetApp自主勒索軟體防護」(ARP/AI)。



=== 新磁碟區預設啟用 ARP/AI

當您在 Workload Factory 控制台中建立新磁碟區時，如果檔案系統具有 ARP/AI 策略，則預設啟用具有 AI (ARP/AI) 的NetApp自主勒索軟體防護。這意味著該卷可以使用人工智慧驅動的偵測和回應功能來自動防禦勒索軟體攻擊。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["在 Workload Factory 中建立卷"]



=== 對不可變文件的複製支持

工作負載工廠支援將不可變磁碟區從一個 FSx for ONTAP 系統複製到另一個 FSx for ONTAP 檔案系統，以保護關鍵資料免遭意外刪除或勒索軟體等惡意攻擊。目標磁碟區及其主機檔案系統將處於不可變狀態（即鎖定狀態），且在保留期結束之前，目標檔案系統中的任何資料都無法修改或刪除。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["了解如何建立複製關係"]



=== 在連結建立期間管理 IAM 執行角色和權限

現在，您可以在 Workload Factory 控制台中建立連結時管理 IAM 執行角色及其附加的權限原則。連結在您的 Workload Factory 帳戶和一個或多個 FSx for ONTAP檔案系統之間建立連線。您有兩種選擇來指派 IAM 執行角色和連結權限 - 自動或使用者提供。在 Workload Factory 中管理執行角色及其附加的權限策略意味著您不再需要使用第三方程式碼。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["使用 Lambda 連結連線至適用於 ONTAP 檔案系統的 FSX"]
